/* Marsad admin shell 3.6.4 */
(()=>{
'use strict';
const $=id=>document.getElementById(id),dashboard=$('dashboard'),tabs=$('tabs');
if(!dashboard||!tabs||dashboard.dataset.shellReady==='364')return;
dashboard.dataset.shellReady='364';
const groups=[
{id:'now',label:'الآن',icon:'●',views:['live'],title:'الآن',desc:'الحالة الحالية والتنبيهات التي تحتاج تدخل'},
{id:'day',label:'أداء اليوم',icon:'↗',views:['queue','metrics','analysis'],title:'أداء اليوم',desc:'مؤشرات الخدمة والموظفين والضغط خلال يوم التشغيل'},
{id:'people',label:'الموظفون',icon:'◎',views:['profile','attendance','shifts'],title:'الموظفون',desc:'ملف الموظف والحضور والبريك والخروج والاستئناف'},
{id:'calls',label:'المكالمات',icon:'☎',views:['calls','missed'],title:'المكالمات',desc:'السجل والمكالمات الفائتة وحالات الموظفين وقتها'},
{id:'action',label:'المتابعة',icon:'✓',views:['followup','messages'],title:'المتابعة',desc:'المشكلات المفتوحة ورسائل الإدارة والتقارير'},
{id:'manage',label:'الإعدادات',icon:'⚙',views:['settings','health','guide','telegram'],title:'الإعدادات',desc:'الموظفون والربط ودقة البيانات وتنبيهات الموبايل'}];
dashboard.classList.add('dashboard-shell');
const sidebar=document.createElement('aside');sidebar.className='dashboard-sidebar';sidebar.id='workspaceSidebar';
const content=document.createElement('div');content.className='dashboard-content';
const backdrop=document.createElement('button');backdrop.type='button';backdrop.className='sidebar-backdrop';backdrop.setAttribute('aria-label','إغلاق القائمة');dashboard.before(backdrop);
const brand=document.createElement('div');brand.className='sidebar-brand';brand.innerHTML='<div class="brand-mark">م</div><div class="brand-copy"><strong>مرصد الأداء</strong><span>إدارة مركز الاتصالات</span></div>';sidebar.appendChild(brand);
const label=document.createElement('div');label.className='sidebar-section-label';label.textContent='القائمة الرئيسية';sidebar.appendChild(label);
const nav=document.createElement('nav');nav.className='workspace-nav';nav.setAttribute('aria-label','القائمة الرئيسية');sidebar.appendChild(nav);
const leaves=[...tabs.querySelectorAll('[data-tab]')];tabs.replaceChildren();nav.appendChild(tabs);
function expandGroup(id){for(const g of groups){const b=nav.querySelector('[data-workspace="'+g.id+'"]'),sub=$('submenu-'+g.id);const open=g.id===id;b.setAttribute('aria-expanded',String(open));sub.hidden=!open;}}
for(const g of groups){const wrap=document.createElement('div');wrap.className='workspace-group';const b=document.createElement('button');b.type='button';b.dataset.workspace=g.id;b.innerHTML='<span class="nav-icon">'+g.icon+'</span><span>'+g.label+'</span><span class="nav-chevron" aria-hidden="true">⌄</span>';b.setAttribute('aria-expanded','false');b.setAttribute('aria-controls','submenu-'+g.id);const sub=document.createElement('div');sub.id='submenu-'+g.id;sub.className='workspace-submenu';sub.hidden=true;for(const leaf of leaves.filter(n=>g.views.includes(n.dataset.tab)))sub.appendChild(leaf);b.onclick=()=>expandGroup(b.getAttribute('aria-expanded')==='true'?'':g.id);wrap.append(b,sub);tabs.appendChild(wrap)}
const subLabel=document.createElement('div');subLabel.className='sidebar-section-label';subLabel.textContent='داخل القسم';subLabel.hidden=true;sidebar.append(subLabel);
const footer=document.createElement('div');footer.className='sidebar-footer';sidebar.appendChild(footer);if($('logoutButton'))footer.appendChild($('logoutButton'));
const top=document.createElement('div');top.className='dashboard-topline';
const heading=document.createElement('div');heading.className='workspace-heading';heading.innerHTML='<h2 id="workspaceTitle">الآن</h2><p id="workspaceDescription">الحالة الحالية والتنبيهات التي تحتاج تدخل</p>';
const topActions=document.createElement('div');topActions.className='topline-actions';
const menu=document.createElement('button');menu.type='button';menu.className='secondary mobile-sidebar-toggle';menu.textContent='القائمة';menu.onclick=()=>document.body.classList.contains('sidebar-open')?closeSidebar():openSidebar();topActions.appendChild(menu);if($('syncStatus'))topActions.appendChild($('syncStatus'));top.append(heading,topActions);content.appendChild(top);
const filters=dashboard.querySelector('.filters');if(filters){filters.classList.add('admin-topbar');const fields=document.createElement('div');fields.className='filter-fields';for(const id of ['day','employeeFilter','queueFilter']){const n=$(id),o=n?.closest('label');if(o)fields.appendChild(o)}const adv=filters.querySelector('.filter-advanced');if(adv)fields.appendChild(adv);const actions=document.createElement('div');actions.className='filter-actions';const da=filters.querySelector('.date-actions');if(da)actions.appendChild(da);for(const id of ['resetFiltersButton','refreshButton'])if($(id))actions.appendChild($(id));const sr=document.createElement('div');sr.className='filter-summary-row';if($('filterSummary'))sr.appendChild($('filterSummary'));if($('periodNote')){$('periodNote').classList.add('period-note-compact');sr.appendChild($('periodNote'))}filters.prepend(fields);filters.append(actions,sr);content.appendChild(filters)}
if($('message'))content.appendChild($('message'));if($('operationsLoad')){$('operationsLoad').classList.add('operations-strip');content.appendChild($('operationsLoad'))}
const toolbar=dashboard.querySelector('.ops-toolbar');if(toolbar){const d=document.createElement('details');d.className='display-preferences';const s=document.createElement('summary');s.textContent='خيارات العرض وحفظ الفلاتر';d.append(s,toolbar);content.appendChild(d)}
for(const section of [...dashboard.querySelectorAll(':scope > .view')])content.appendChild(section);dashboard.append(sidebar,content);
function openSidebar(){document.body.classList.add('sidebar-open')}function closeSidebar(){document.body.classList.remove('sidebar-open')}backdrop.onclick=closeSidebar;window.addEventListener('resize',()=>{if(innerWidth>820)closeSidebar()});
for(const section of document.querySelectorAll('.view'))for(const p of [...section.children].filter(e=>e.tagName==='P'&&(e.classList.contains('muted')||e.classList.contains('source-note'))&&e.getAttribute('role')!=='status')){if(p.closest('details'))continue;const d=document.createElement('details');d.className='help-detail';const s=document.createElement('summary');s.textContent='طريقة الحساب والتوضيح';p.before(d);d.append(s,p)}
const liveDetails=$('attentionDetails');if(liveDetails&&!liveDetails.closest('details')){const d=document.createElement('details');d.className='detail-panel';const s=document.createElement('summary');s.textContent='تفاصيل التنبيهات والإجراءات';liveDetails.before(d);d.append(s,liveDetails)}
for(const cards of document.querySelectorAll('.cards')){if(cards.dataset.compactReady)continue;cards.dataset.compactReady='1';cards.classList.add('summary-cards');const b=document.createElement('button');b.type='button';b.className='secondary indicators-toggle';b.textContent='باقي المؤشرات';cards.after(b);const sync=()=>b.hidden=cards.children.length<=6;new MutationObserver(sync).observe(cards,{childList:true});sync();b.onclick=()=>{const x=cards.classList.toggle('expanded');b.textContent=x?'اختصار المؤشرات':'باقي المؤشرات'}}
const collapsible={metricRows:'تفاصيل أداء الموظفين',callRows:'سجل المكالمات بالتفصيل',attendanceRows:'تفاصيل الحضور والبريك',shiftRows:'تفاصيل الخروج واستئناف العمل',queueRows:'تفاصيل مؤشرات أنواع الطلبات',missedRows:'قائمة المكالمات الفائتة',rosterRows:'قائمة الموظفين',reviewRows:'قائمة المتابعات',connectionRows:'تفاصيل الربط بالأجهزة',unattributedRows:'المكالمات غير المنسوبة',customerRows:'تكرار اتصالات العملاء'};
for(const [id,title] of Object.entries(collapsible)){const body=$(id),wrap=body?.closest('.tablewrap');if(!wrap||wrap.closest('details'))continue;const d=document.createElement('details');d.className='auto-detail';const s=document.createElement('summary');s.textContent=title;wrap.before(d);d.append(s,wrap)}
const welcome=document.createElement('section');welcome.className='panel workspace-welcome';welcome.innerHTML='<h2>أهلًا بك في مرصد الأداء</h2><p>افتح قسمًا من القائمة، ثم اختر الصفحة التي تريد عرضها.</p>';content.appendChild(welcome);
const baseShowTab=showTab;showTab=function(view){const group=groups.find(g=>g.views.includes(view));if(!group)return;baseShowTab(view);welcome.hidden=true;expandGroup(group.id);for(const b of nav.querySelectorAll('[data-workspace]'))b.classList.toggle('selected',b.dataset.workspace===group.id);for(const b of tabs.querySelectorAll('[data-tab]')){b.setAttribute('aria-current',b.dataset.tab===view?'page':'false');}tabs.hidden=false;subLabel.hidden=true;$('workspaceTitle').textContent=group.title;$('workspaceDescription').textContent=tabs.querySelector('[data-tab="'+view+'"]')?.textContent||group.desc;closeSidebar()};
function showHome(){for(const section of document.querySelectorAll('.view'))section.hidden=true;welcome.hidden=false;expandGroup('');$('workspaceTitle').textContent='مرصد الأداء';$('workspaceDescription').textContent='اختر القسم ثم الصفحة';for(const b of tabs.querySelectorAll('button'))b.classList.remove('selected');}
function foldTables(){for(const wrap of content.querySelectorAll('.view .tablewrap')){const heads=[...wrap.querySelectorAll('thead th')].map(th=>[...th.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim()||th.textContent.replace('فلتر','').trim());for(const tr of wrap.querySelectorAll('tbody tr'))for(const [i,td] of [...tr.children].entries()){const label=heads[i]||'';if(td.getAttribute('data-label')!==label)td.setAttribute('data-label',label);}if(wrap.closest('details')||wrap.closest('#contextPanel'))continue;const d=document.createElement('details');d.className='auto-detail';const summary=document.createElement('summary');summary.textContent='عرض التفاصيل';wrap.before(d);d.append(summary,wrap);}}
foldTables();new MutationObserver(foldTables).observe(content,{childList:true,subtree:true});
for(const d of document.querySelectorAll('details')){d.open=false;const summary=d.querySelector(':scope > summary');if(summary&&!summary.textContent.startsWith('عرض التفاصيل')&&!d.classList.contains('filter-advanced'))summary.textContent='عرض التفاصيل — '+summary.textContent;}
const expanded=new Set();function compactGroups(){const root=$('employeeLiveGroups');if(!root)return;for(const group of root.querySelectorAll('.employee-group')){if(group.dataset.compactApplied)continue;group.dataset.compactApplied='1';const items=[...group.querySelectorAll('.employee-tile')],state=[...group.classList].find(c=>c.startsWith('state-'))?.slice(6)||'';group.classList.add('employee-group-collapsible');const h=group.querySelector('h4'),b=document.createElement('button');if(!h)continue;b.type='button';b.className='secondary employee-group-toggle';const sync=()=>{const open=expanded.has(state);group.classList.toggle('employee-group-open',open);b.textContent=open?'إخفاء القائمة':'عرض القائمة'};b.onclick=()=>{expanded.has(state)?expanded.delete(state):expanded.add(state);sync()};h.appendChild(b);sync()}}
if($('employeeLiveGroups')){new MutationObserver(compactGroups).observe($('employeeLiveGroups'),{childList:true,subtree:true});compactGroups()}
const update=()=>document.body.classList.toggle('dashboard-active',!dashboard.hidden);new MutationObserver(update).observe(dashboard,{attributes:true,attributeFilter:['hidden']});update();
window.MarsadAdminUI={$,dashboard,tabs,groups,nav,topActions,subLabel,showHome,showBase:view=>showTab(view)};
showHome();
})();

