/* Marsad admin compact content 3.7.2 — restores explicit open/close controls for long content. */
(()=>{'use strict';
const $=id=>document.getElementById(id);if(document.documentElement.dataset.marsadCompact==='372')return;document.documentElement.dataset.marsadCompact='372';
const style=document.createElement('style');style.textContent=`
.compact-content-toggle{display:flex;width:100%;align-items:center;justify-content:space-between;gap:10px;margin:8px 0 6px;padding:10px 12px;background:#10283a;color:#d8e9f7;border:1px solid #2d4d65;border-radius:10px;font-weight:700;text-align:right}
.compact-content-toggle:after{content:'فتح القائمة';font-size:11px;color:#83a1b8;font-weight:600}.compact-content-toggle[aria-expanded="true"]:after{content:'إخفاء القائمة'}
.compact-collapsed[hidden]{display:none!important}.compact-group-toggle{margin-inline-start:auto;min-height:30px!important;padding:5px 8px!important;font-size:11px!important}.employee-group .employee-tiles[hidden]{display:none!important}
`;document.head.appendChild(style);
const titles={liveStaffDetails:'حالة الموظفين والشيفت والبريك',liveRows:'تفاصيل الموظفين والمكالمات والتحويلات',queueLiveRows:'المكالمات الجارية الآن',metricRows:'تفاصيل أداء الفريق',profileSessionRows:'الدخول والخروج وبدء الاستقبال',profileCallRows:'مكالمات الموظف',profileStateRows:'الحالات ومددها',attendanceRows:'تفاصيل الحضور والبريك',breakOverlapRows:'تداخل البريكات والتغطية',shiftRows:'تفاصيل الشيفتات',handoverRows:'تسليم التحويلة بين الموظفين',queueRows:'تفاصيل نتيجة أنواع الطلبات',pressureRows:'تفاصيل الضغط والتغطية',queueSampleRows:'عينات انتظار العملاء',callRows:'سجل المكالمات بالتفصيل',attributionRows:'تفاصيل ربط المكالمات بالموظفين',missedRows:'المكالمات الفائتة بالتفصيل',contextRows:'حالة الموظفين وقت المكالمة',unattributedRows:'المكالمات غير المنسوبة',customerRows:'اتصالات العملاء',reviewRows:'قائمة المتابعات',savedReportRows:'التقارير المحفوظة',auditRows:'سجل تغييرات الإدارة',connectionRows:'اتصال الموظفين بأرابيكس',formulaRows:'المكالمات المستخدمة في الحساب',tgAlertRows:'سجل تنبيهات Telegram',accessRows:'مستخدمو صفحة الإدارة',rosterRows:'قائمة موظفي التشغيل',unavailabilityRows:'فترات عدم الإتاحة',extensionUsageRows:'مدة العمل على كل تحويلة',extensionUsageAllRows:'مدد الفريق على التحويلات',extensionSessionRows:'كل جلسة على التحويلات',messageRows:'سجل رسائل الموظفين'};
const defaultOpen=new Set(['waitingRows']);
function addToggle(id){const body=$(id),wrap=body?.closest('.tablewrap');if(!wrap||wrap.dataset.compact372==='1')return;wrap.dataset.compact372='1';wrap.classList.add('compact-collapsed');const button=document.createElement('button');button.type='button';button.className='compact-content-toggle';button.dataset.compactTarget=id;button.textContent=titles[id]||'عرض التفاصيل';const set=open=>{wrap.hidden=!open;button.setAttribute('aria-expanded',String(open));};set(defaultOpen.has(id));button.onclick=()=>set(wrap.hidden);wrap.before(button);}
function compactTables(){for(const id of Object.keys(titles))addToggle(id);}
const openGroups=new Set(['state-action']);
function compactEmployeeGroups(){const root=$('employeeLiveGroups');if(!root)return;for(const group of root.querySelectorAll('.employee-group')){if(group.tagName==='DETAILS')continue;if(group.dataset.compact372==='1')continue;const tiles=group.querySelector('.employee-tiles'),head=group.querySelector('h4');if(!tiles||!head)continue;group.dataset.compact372='1';const state=[...group.classList].find(c=>c.startsWith('state-'))||'';const button=document.createElement('button');button.type='button';button.className='secondary compact-group-toggle';const set=open=>{tiles.hidden=!open;button.textContent=open?'إخفاء القائمة':'فتح القائمة';button.setAttribute('aria-expanded',String(open));};set(openGroups.has(state));button.onclick=e=>{e.stopPropagation();const open=tiles.hidden;if(open)openGroups.add(state);else openGroups.delete(state);set(open);};head.appendChild(button);}}
compactTables();compactEmployeeGroups();
const content=document.querySelector('.dashboard-content')||document.body;let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;compactTables();compactEmployeeGroups();});}).observe(content,{childList:true,subtree:true});
window.addEventListener('kpi-admin-refresh',()=>{compactTables();compactEmployeeGroups();});
})();
