/* Server-enforced password-only administration. Never stores a master password in a role profile. */
(()=>{
'use strict';
const U=window.MarsadAdminUI;if(!U)return;const {$,dashboard,tabs,groups,nav,topActions}=U;
const labels={admin:'مدير',supervisor:'مشرف',viewer:'مشاهدة فقط'};
let who=null,busy=false,lastToken='';
const permitted=v=>who?.role==='admin'||!['settings','telegram','health','guide'].includes(v);
const writes=()=>who?.role==='admin'||who?.role==='supervisor';
const style=document.createElement('style');style.textContent='.admin-permission-hidden{display:none!important}.access-panel{padding:16px;border:1px solid #31516a;border-radius:14px;margin-bottom:16px}.access-create{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.access-create label{display:grid;gap:5px}.access-create input,.access-create select{min-height:42px;width:100%;padding:8px}.access-role-badge{padding:8px;border:1px solid #31516a;border-radius:10px;font-size:14px}@media(max-width:520px){.access-create{grid-template-columns:1fr}}';document.head.append(style);
const hide=(e,yes)=>e?.classList.toggle('admin-permission-hidden',yes);
function apply(){
 document.body.dataset.adminRole=who?.role||'viewer';
 for(const e of tabs.querySelectorAll('[data-tab]'))hide(e,!permitted(e.dataset.tab));
 for(const e of nav.querySelectorAll('[data-workspace]')){const g=groups.find(v=>v.id===e.dataset.workspace);hide(e,!g?.views.some(permitted))}
 hide($('adminAccessPanel'),who?.role!=='admin');
 document.querySelectorAll('[data-shift-action],[data-shift],#newReviewButton,#saveReviewButton,#saveReportButton,#sendMessageButton,#saveMessageButton,#messageForm button[type=submit],[data-ops-review],[data-ops-incident]').forEach(e=>hide(e,!writes()));
 document.querySelectorAll('#settings button,#settings form button,#telegram button,[data-delete],[data-pin],[data-employee]').forEach(e=>hide(e,who?.role!=='admin'));
 let badge=document.querySelector('.access-role-badge');if(!badge){badge=document.createElement('span');badge.className='access-role-badge';topActions.prepend(badge)}
 const text=who?who.name+' · '+labels[who.role]:'التحقق من الصلاحية';if(badge.textContent!==text)badge.textContent=text;
}
const originalShow=showTab;
showTab=function(view){if(!permitted(view))view='live';originalShow(view);apply()};
function panel(){if($('adminAccessPanel'))return;const s=$('settings');if(!s)return;const d=document.createElement('section');d.id='adminAccessPanel';d.className='access-panel';
 d.innerHTML='<h2>مستخدمو الإدارة</h2><p class="muted">الدخول بالباسورد فقط من أي جهاز. كل باسورد لازم يكون مختلفًا؛ الصلاحيات محفوظة ومطبقة على الخادم.</p><form id="accessForm" class="access-create"><label>اسم المستخدم<input id="accessName" maxlength="100" required></label><label>الدور<select id="accessRole"><option value="supervisor">مشرف</option><option value="viewer">مشاهدة فقط</option><option value="admin">مدير</option></select></label><label>الباسورد<input id="accessPassword" type="password" maxlength="200" autocomplete="new-password" required></label><label>تأكيد الباسورد<input id="accessConfirm" type="password" maxlength="200" autocomplete="new-password" required></label><button type="submit">إنشاء مستخدم</button></form><p id="accessMessage" role="status"></p><div class="tablewrap"><table><thead><tr><th>الاسم</th><th>الدور</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody id="accessRows"></tbody></table></div><dialog id="accessEdit"><form id="accessEditForm"><h3 id="accessEditName"></h3><label>الدور<select id="accessEditRole"><option value="admin">مدير</option><option value="supervisor">مشرف</option><option value="viewer">مشاهدة فقط</option></select></label><label>باسورد جديد — اتركه فارغًا لإبقاء الحالي<input id="accessEditPassword" type="password" maxlength="200" autocomplete="new-password"></label><label>تأكيد الباسورد<input id="accessEditConfirm" type="password" maxlength="200" autocomplete="new-password"></label><p id="accessEditMessage" role="status"></p><button type="submit">حفظ</button><button type="button" id="accessEditCancel">إلغاء</button></form></dialog>';s.prepend(d);
 $('accessForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/admin-access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('accessName').value,role:$('accessRole').value,password:$('accessPassword').value,confirmation:$('accessConfirm').value})});$('accessPassword').value='';$('accessConfirm').value='';$('accessName').value='';await load(true);$('accessMessage').textContent='تم إنشاء المستخدم. يدخل من نفس رابط الإدارة بالباسورد فقط.'}catch(err){$('accessMessage').textContent=err.message}finally{button.disabled=false}};
 $('accessEditCancel').onclick=()=>{$('accessEdit').close();$('accessEditPassword').value='';$('accessEditConfirm').value=''};
}
async function change(id,values,method='PATCH'){await api('/api/admin-access',{method,headers:{'content-type':'application/json'},body:JSON.stringify({id,...values})});await load(true)}
function rows(accounts){$('accessRows').innerHTML=accounts.map(a=>'<tr><td>'+esc(a.name)+'</td><td>'+esc(labels[a.role]||a.role)+'</td><td>'+(a.active?'مفعّل':'معطّل')+'</td><td><button data-edit="'+a.id+'">الدور / الباسورد</button> <button data-active="'+a.id+'">'+(a.active?'تعطيل':'تفعيل')+'</button> <button data-remove="'+a.id+'">حذف</button></td></tr>').join('')||'<tr><td colspan="4">لا يوجد مستخدمون إضافيون. الباسورد الرئيسي محتفظ بصلاحيته.</td></tr>';
 for(const el of $('accessRows').querySelectorAll('button'))el.onclick=async()=>{const a=accounts.find(v=>v.id===Number(el.dataset.edit||el.dataset.active||el.dataset.remove));if(!a)return;try{
  if(el.dataset.edit){$('accessEditName').textContent=a.name;$('accessEditRole').value=a.role;$('accessEditPassword').value='';$('accessEditConfirm').value='';$('accessEditMessage').textContent='';$('accessEdit').showModal();$('accessEditForm').onsubmit=async e=>{e.preventDefault();const values={role:$('accessEditRole').value};if($('accessEditPassword').value){values.password=$('accessEditPassword').value;values.confirmation=$('accessEditConfirm').value}try{await change(a.id,values);$('accessEdit').close();$('accessEditPassword').value='';$('accessEditConfirm').value='';$('accessMessage').textContent='تم الحفظ. الجلسات السابقة لهذا المستخدم انتهت.'}catch(err){$('accessEditMessage').textContent=err.message}};return}
  if(el.dataset.remove){if(!confirm('حذف مستخدم الإدارة «'+a.name+'»؟ سجله السابق محفوظ.'))return;await change(a.id,{},'DELETE')}else{await change(a.id,{active:!a.active})}
 }catch(err){$('accessMessage').textContent=err.message}};
}
async function load(force=false){const token=sessionStorage.getItem('adminPassword');if(!token){who=null;lastToken='';apply();return}if(busy)return;if(!force&&token===lastToken){apply();return}busy=true;try{const d=await api('/api/admin-access');who=d.identity;lastToken=token;sessionStorage.setItem('marsadAdminIdentity',JSON.stringify(who));if(who.role==='admin')rows(d.accounts||[]);apply()}catch(err){who=null;lastToken='';apply();if($('accessMessage'))$('accessMessage').textContent=err.message}finally{busy=false}}
 $('loginButton').onclick=async()=>{const button=$('loginButton');button.disabled=true;$('loginError').textContent='';try{const r=await fetch(API+'/api/admin-access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',password:$('password').value}),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الدخول');sessionStorage.setItem('adminPassword',d.token);sessionStorage.removeItem('marsadAdminRoleProfile');who=d.identity;lastToken='';$('password').value='';$('login').hidden=true;dashboard.hidden=false;await load(true);window.MarsadAdminUI?.showHome();await refresh(true)}catch(err){$('loginError').textContent=err.message}finally{button.disabled=false}};
 $('password')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();$('loginButton').click()}},{capture:true});
 $('logoutButton')?.addEventListener('click',()=>{const token=lastToken;if(token)fetch(API+'/api/admin-access',{method:'POST',headers:{'content-type':'application/json','x-admin-password':token},body:JSON.stringify({action:'logout'}),keepalive:true}).catch(()=>{});who=null;lastToken='';sessionStorage.removeItem('marsadAdminIdentity');apply()});
 panel();new MutationObserver(apply).observe(dashboard,{childList:true,subtree:true});window.addEventListener('kpi-admin-refresh',()=>load());load();
})();

