/* Marsad derived admin views 3.6.4 */
(()=>{
'use strict';
const U=window.MarsadAdminUI;if(!U)return;const {$}=U;
const people=()=>new Map((typeof staff!=='undefined'?staff:[]).map(e=>[Number(e.id),e])),emp=()=>Number($('employeeFilter')?.value||0),ext=()=>String($('extensionFilter')?.value||'').trim(),scope=r=>(!emp()||Number(r.employeeId)===emp())&&(!ext()||String(r.extension||'')===ext()),sec=v=>Number.isFinite(Number(v))?Math.max(0,Number(v)):0,min=(a,b)=>!a?b:!b?a:(Date.parse(a)<=Date.parse(b)?a:b),max=(a,b)=>!a?b:!b?a:(Date.parse(a)>=Date.parse(b)?a:b);
function ensure(){const a=$('attendance');if(a&&!$('unavailabilityPanel')){const d=document.createElement('details');d.id='unavailabilityPanel';d.className='detail-panel management-derived';d.innerHTML='<summary>وقت عدم الإتاحة / انقطاع الرصد</summary><p class="muted">الفترات التي سجلها النظام كـ «انقطاع رصد». قد يكون السبب إغلاق المتصفح أو السيستم أو الاتصال؛ السبب نفسه لا يُفترض بدون دليل.</p><div id="unavailabilityCards" class="cards"></div><div class="tablewrap"><table><thead><tr><th>الموظف</th><th>التحويلة</th><th>المدة</th><th>عدد الفترات</th><th>أول انقطاع</th><th>آخر رصد</th></tr></thead><tbody id="unavailabilityRows"></tbody></table></div>';($('attendanceCoverage')||a.firstElementChild)?.insertAdjacentElement('afterend',d)}const p=$('profile');if(p&&!$('extensionUsagePanel')){const d=document.createElement('details');d.id='extensionUsagePanel';d.className='detail-panel management-derived';d.innerHTML='<summary>مدة العمل على كل تحويلة</summary><div id="extensionUsageCards" class="cards"></div><div class="tablewrap"><table><thead><tr><th>الموظف</th><th>التحويلة</th><th>إجمالي المدة</th><th>الجلسات</th><th>أول دخول</th><th>آخر رصد/خروج</th></tr></thead><tbody id="extensionUsageRows"></tbody></table></div>';p.querySelector('#profileCards')?.insertAdjacentElement('afterend',d)}const m=$('metrics');if(m&&!$('extensionUsageAllPanel')){const d=document.createElement('details');d.id='extensionUsageAllPanel';d.className='detail-panel management-derived';d.innerHTML='<summary>كل الموظفين × التحويلات</summary><div id="extensionUsageAllCards" class="cards"></div><div class="tablewrap"><table><thead><tr><th>الموظف</th><th>التحويلة</th><th>إجمالي المدة</th><th>الجلسات</th></tr></thead><tbody id="extensionUsageAllRows"></tbody></table></div>';m.querySelector('#metricCards')?.insertAdjacentElement('afterend',d)}}
function render(){ensure();const states=(typeof daily!=='undefined'&&daily?.attendance?.states)||[],ps=people(),g=new Map();for(const s of states){if(s.state!=='unknown'||!scope(s))continue;const k=s.employeeId+'|'+(s.extension||'—'),x=g.get(k)||{employeeId:Number(s.employeeId),extension:s.extension||'—',seconds:0,count:0,first:null,last:null};x.seconds+=sec(s.durationSeconds);x.count++;x.first=min(x.first,s.startedAt);x.last=max(x.last,s.endedAt||s.evidenceUntil||s.startedAt);g.set(k,x)}const ur=[...g.values()].sort((a,b)=>b.seconds-a.seconds),ub=$('unavailabilityRows'),uc=$('unavailabilityCards');if(ub&&uc){const total=ur.reduce((n,r)=>n+r.seconds,0);uc.innerHTML=[['إجمالي عدم الإتاحة',fmt(total)],['موظفون لديهم انقطاع',new Set(ur.map(r=>r.employeeId)).size],['فترات الانقطاع',ur.reduce((n,r)=>n+r.count,0)]].map(([k,v])=>'<div class="card">'+k+'<span>'+v+'</span></div>').join('');ub.innerHTML=ur.map(r=>'<tr><td>'+esc(ps.get(r.employeeId)?.name||'اسم غير متاح')+'</td><td>'+esc(r.extension)+'</td><td>'+fmt(r.seconds)+'</td><td>'+r.count+'</td><td>'+at(r.first)+'</td><td>'+at(r.last)+'</td></tr>').join('')||'<tr><td colspan="6">لا توجد فترات انقطاع رصد.</td></tr>'}const sessions=(typeof daily!=='undefined'&&daily?.attendance?.sessions)||[],eg=new Map();for(const s of sessions){if(!scope(s))continue;const e=String(s.extension||'—'),k=s.employeeId+'|'+e,x=eg.get(k)||{employeeId:Number(s.employeeId),extension:e,seconds:0,count:0,first:null,last:null};x.seconds+=sec(s.daySeconds??s.durationSeconds);x.count++;x.first=min(x.first,s.workStartedAt||s.issuedAt||s.startedAt);x.last=max(x.last,s.endedAt||s.observedThrough||s.lastSeen||s.workStartedAt||s.issuedAt);eg.set(k,x)}const rows=[...eg.values()].map(r=>({...r,name:ps.get(r.employeeId)?.name||'اسم غير متاح'})).sort((a,b)=>a.name.localeCompare(b.name,'ar')||b.seconds-a.seconds),selected=emp()?rows.filter(r=>r.employeeId===emp()):rows;const draw=(bid,cid,list,full)=>{const b=$(bid),c=$(cid);if(!b||!c)return;c.innerHTML=[['إجمالي المدة',fmt(list.reduce((n,r)=>n+r.seconds,0))],['عدد التحويلات',new Set(list.map(r=>r.extension)).size]].map(([k,v])=>'<div class="card">'+k+'<span>'+v+'</span></div>').join('');b.innerHTML=list.map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+esc(r.extension)+'</td><td>'+fmt(r.seconds)+'</td><td>'+r.count+'</td>'+(full?'<td>'+at(r.first)+'</td><td>'+at(r.last)+'</td>':'')+'</tr>').join('')||'<tr><td colspan="'+(full?6:4)+'">لا توجد جلسات مطابقة.</td></tr>'};draw('extensionUsageRows','extensionUsageCards',selected,true);draw('extensionUsageAllRows','extensionUsageAllCards',rows,false);const lc=$('liveCards');if(lc){let card=lc.querySelector('[data-derived-unavailability]');if(!card){card=document.createElement('div');card.className='card';card.dataset.derivedUnavailability='1';lc.appendChild(card)}card.innerHTML='عدم الإتاحة المرصود<span>'+fmt(ur.reduce((n,r)=>n+r.seconds,0))+'</span>'}}
ensure();window.addEventListener('kpi-admin-refresh',render);for(const id of ['employeeFilter','extensionFilter','day'])$(id)?.addEventListener('change',render);render();
})();

