/* Marsad password-only admin access profiles 3.6.2.
   Operational/UI roles only; the existing server still authenticates with its master admin password. */
(()=>{
'use strict';
const U=window.MarsadAdminUI;if(!U)return;const {$,dashboard,tabs,groups,nav,topActions}=U;
const STORE='marsad-admin-access-v1',ROLE_SESSION='marsadAdminRoleProfile';
const presets={
 manager:{label:'مدير',views:groups.flatMap(g=>g.views),writes:'all'},
 supervisor:{label:'مشرف',views:['live','queue','metrics','analysis','profile','attendance','shifts','calls','missed','followup','messages'],writes:'supervisor'},
 viewer:{label:'مشاهدة فقط',views:['live','queue','metrics','analysis','profile','attendance','shifts','calls','missed'],writes:'none'}
};
const style=document.createElement('style');style.textContent='.access-role-badge{display:inline-flex;align-items:center;min-height:34px;padding:6px 10px;border:1px solid #34566e;border-radius:10px;background:#0f2638;color:#cde8f5;font-size:12px;font-weight:800}.access-panel{margin:0 0 16px;padding:16px;border:1px solid #31516a;border-radius:14px;background:#0b1b2a}.access-create{display:grid;grid-template-columns:minmax(180px,1fr) minmax(150px,.7fr) minmax(180px,1fr) auto;gap:9px;align-items:end;margin:10px 0 12px}.access-create label{font-size:12px;color:#b8c9d9}.access-create input,.access-create select{width:100%;margin-top:5px;min-height:42px;background:#091623;border:1px solid #35526a;color:#eef6ff;border-radius:9px;padding:9px 10px}.access-panel #accessMessage{min-height:24px;color:#9ee8d7;font-size:12px}.role-session #adminAccessPanel{display:none!important}@media(max-width:900px){.access-create{grid-template-columns:1fr 1fr}.access-create button{grid-column:1/-1}}@media(max-width:520px){.access-create{grid-template-columns:1fr}}';document.head.appendChild(style);
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb=s=>Uint8Array.from(atob(String(s).replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-String(s).length%4)%4)),c=>c.charCodeAt(0));
const profiles=()=>{try{const v=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
const save=v=>localStorage.setItem(STORE,JSON.stringify(v));
async function key(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:160000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function seal(master,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(password,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(master));return{salt:b64(salt),iv:b64(iv),cipher:b64(cipher)}}
async function open(p,password){try{return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb(p.iv)},await key(password,unb(p.salt)),unb(p.cipher)))}catch{return null}}
const active=()=>{const id=sessionStorage.getItem(ROLE_SESSION);return id?profiles().find(p=>p.id===id)||null:null};
const preset=()=>{const p=active();return p?presets[p.role]||presets.viewer:null};
const canView=v=>!preset()||preset().views.includes(v);
function canWrite(path,method='GET'){if(String(method).toUpperCase()==='GET')return true;const r=preset();if(!r||r.writes==='all')return true;if(r.writes==='none')return false;if(path.startsWith('/api/employees')||path.startsWith('/api/telegram'))return false;return ['/api/operations','/api/messages','/api/shifts'].some(x=>path.startsWith(x))}
const baseShowTab=showTab;
showTab=function(view){if(!canView(view))view=preset()?.views.find(v=>$(v))||'live';baseShowTab(view);for(const b of tabs.querySelectorAll('[data-tab]'))if(preset()&&!preset().views.includes(b.dataset.tab))b.hidden=true;applyRole()};
function applyRole(){const p=active(),r=preset();document.body.classList.toggle('role-session',!!p);document.body.dataset.adminRole=p?.role||'owner';for(const b of nav.querySelectorAll('[data-workspace]')){const g=groups.find(x=>x.id===b.dataset.workspace);b.hidden=!!r&&!g.views.some(v=>r.views.includes(v))}let badge=document.querySelector('.access-role-badge');if(!badge){badge=document.createElement('span');badge.className='access-role-badge';topActions.prepend(badge)}badge.textContent=p?p.name+' · '+(presets[p.role]?.label||p.role):'مدير النظام';if($('adminAccessPanel'))$('adminAccessPanel').hidden=!!p;const ro=r?.writes==='none',sup=r?.writes==='supervisor';document.querySelectorAll('[data-shift-action],#newReviewButton,#saveReportButton,#messageForm button[type=submit],#saveMessageButton').forEach(e=>{if(ro)e.hidden=true});if(ro||sup)document.querySelectorAll('#settings button,#settings form button,#telegram button').forEach(e=>e.hidden=true)}
function ensureAccess(){const s=$('settings');if(!s||$('adminAccessPanel'))return;const d=document.createElement('section');d.id='adminAccessPanel';d.className='access-panel';d.innerHTML='<div class="section-head"><h2>صلاحيات دخول الإدارة</h2></div><p class="muted">أنشئ دخولًا مستقلًا بباسورد فقط. مدير: كامل. مشرف: متابعة ورسائل بدون إدارة الموظفين أو إعدادات تليجرام. مشاهدة: قراءة فقط.</p><div class="access-create"><label>اسم المستخدم<input id="accessName" maxlength="80" placeholder="مثال: تيم ليدر مساء"></label><label>الصلاحية<select id="accessRole"><option value="supervisor">مشرف</option><option value="viewer">مشاهدة فقط</option><option value="manager">مدير</option></select></label><label>الباسورد<input id="accessPassword" type="password" minlength="4" autocomplete="new-password"></label><button id="accessCreateButton" type="button">إنشاء صلاحية</button></div><p id="accessMessage"></p><div class="tablewrap"><table><thead><tr><th>الاسم</th><th>الصلاحية</th><th>الإنشاء</th><th>الإجراء</th></tr></thead><tbody id="accessRows"></tbody></table></div>';s.prepend(d);$('accessCreateButton').onclick=createProfile;renderProfiles()}
const pack=p=>b64(enc.encode(JSON.stringify(p))),link=p=>{const u=new URL(location.href);u.hash='marsad-access='+pack(p);return u.toString()};
async function createProfile(){const name=$('accessName').value.trim(),role=$('accessRole').value,password=$('accessPassword').value,master=sessionStorage.getItem('adminPassword');if(!name||password.length<4||!presets[role]||!master){$('accessMessage').textContent='اكتب الاسم والباسورد وأنت داخل بحساب مدير النظام.';return}const p={id:crypto.randomUUID(),name,role,createdAt:new Date().toISOString(),...(await seal(master,password))},v=profiles();v.push(p);save(v);$('accessPassword').value='';$('accessName').value='';renderProfiles();$('accessMessage').textContent='تم. انسخ رابط الدخول وأرسله للشخص؛ بعد فتحه مرة واحدة يدخل بالباسورد فقط.'}
function renderProfiles(){const b=$('accessRows');if(!b)return;b.innerHTML=profiles().map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(presets[p.role]?.label||p.role)+'</td><td>'+at(p.createdAt)+'</td><td><button class="secondary" data-copy="'+p.id+'">نسخ رابط الدخول</button> <button class="secondary" data-del="'+p.id+'">حذف</button></td></tr>').join('')||'<tr><td colspan="4">لا توجد صلاحيات إضافية.</td></tr>';b.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{const p=profiles().find(v=>v.id===x.dataset.copy);if(!p)return;const u=link(p);try{await navigator.clipboard.writeText(u);$('accessMessage').textContent='تم نسخ رابط الدخول.'}catch{$('accessMessage').textContent=u}});b.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{const p=profiles().find(v=>v.id===x.dataset.del);if(!p||!confirm('حذف صلاحية '+p.name+'؟'))return;save(profiles().filter(v=>v.id!==p.id));renderProfiles()})}
const hm=location.hash.match(/^#?marsad-access=([A-Za-z0-9_-]+)$/);if(hm)try{const p=JSON.parse(dec.decode(unb(hm[1])));if(p?.id&&p?.cipher&&presets[p.role]){const v=profiles().filter(x=>x.id!==p.id);v.push(p);save(v);history.replaceState(null,'',location.pathname+location.search);setTimeout(()=>{if($('loginError'))$('loginError').textContent='تم استلام صلاحية «'+p.name+'». اكتب الباسورد للدخول.'},0)}}catch{history.replaceState(null,'',location.pathname+location.search)}
if($('loginButton'))$('loginButton').onclick=async()=>{const entered=$('password').value;$('loginError').textContent='';$('loginButton').disabled=true;try{let r=await fetch(API+'/api/dashboard',{headers:{'x-admin-password':entered},cache:'no-store'});if(r.ok){sessionStorage.setItem('adminPassword',entered);sessionStorage.removeItem(ROLE_SESSION);$('password').value='';$('login').hidden=true;dashboard.hidden=false;await refresh(true);ensureAccess();applyRole();return}for(const p of profiles()){const master=await open(p,entered);if(!master)continue;r=await fetch(API+'/api/dashboard',{headers:{'x-admin-password':master},cache:'no-store'});if(!r.ok)continue;sessionStorage.setItem('adminPassword',master);sessionStorage.setItem(ROLE_SESSION,p.id);$('password').value='';$('login').hidden=true;dashboard.hidden=false;await refresh(true);applyRole();return}throw Error('الباسورد غير صحيح أو الصلاحية غير موجودة على هذا الجهاز')}catch(e){$('loginError').textContent=e.message}finally{$('loginButton').disabled=false}};
$('password')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();$('loginButton').click()}},{capture:true});
$('logoutButton')?.addEventListener('click',()=>sessionStorage.removeItem(ROLE_SESSION));
ensureAccess();const realApi=window.api;if(typeof realApi==='function')window.api=async(path,options={})=>{if(!canWrite(path,options.method||'GET'))throw Error('ليس لديك صلاحية تنفيذ هذا الإجراء');return realApi(path,options)};applyRole();showTab(document.querySelector('#tabs button.selected')?.dataset.tab||'live');
})();
