/* Marsad admin shell 3.6.2 */
(()=>{
'use strict';
const $=id=>document.getElementById(id),dashboard=$('dashboard'),tabs=$('tabs');
if(!dashboard||!tabs||dashboard.dataset.shellReady==='362')return;
dashboard.dataset.shellReady='362';
const groups=[
{id:'now',label:'الآن',icon:'●',views:['live'],title:'الآن',desc:'الحالة الحالية والتنبيهات التي تحتاج تدخل'},
{id:'day',label:'أداء اليوم',icon:'↗',views:['queue','metrics','analysis'],title:'أداء اليوم',desc:'مؤشرات الخدمة والموظفين والضغط خلال يوم التشغيل'},
{id:'people',label:'الموظفون',icon:'◎',views:['profile','attendance','shifts'],title:'الموظفون',desc:'ملف الموظف والحضور والبريك والخروج والاستئناف'},
{id:'calls',label:'المكالمات',icon:'☎',views:['calls','missed'],title:'المكالمات',desc:'السجل والمكالمات الفائتة وحالات الموظفين وقتها'},
{id:'action',label:'المتابعة',icon:'✓',views:['followup','messages'],title:'المتابعة',desc:'المشكلات المفتوحة ورسائل الإدارة والتقارير'},
{id:'manage',label:'الإعدادات',icon:'⚙',views:['settings','health','guide','telegram'],title:'الإعدادات',desc:'الموظفون والربط ودقة البيانات وتنبيهات الموبايل'}];
dashboard.classList.add('dashboard-shell');
const sidebar=document.createElement('aside');sidebar.className='dashboard-sidebar';sidebar.id='workspaceSidebar';
const content=document.createElement('div');content.className='dashboard-content';
const backdrop=document.createElement('button');backdrop.type='button';backdrop.className='sidebar-backdrop';backdrop.setAttribute('aria-label','إغلاق القائمة');dashboard.before(backdrop);
const brand=document.createElement('div');brand.className='sidebar-brand';brand.innerHTML='<div class="brand-mark">م</div><div class="brand-copy"><strong>مرصد الأداء</strong><span>إدارة الكول سنتر</span></div>';sidebar.appendChild(brand);
const label=document.createElement('div');label.className='sidebar-section-label';label.textContent='القائمة الرئيسية';sidebar.appendChild(label);
const nav=document.createElement('nav');nav.className='workspace-nav';nav.setAttribute('aria-label','القائمة الرئيسية');sidebar.appendChild(nav);
for(const g of groups){const b=document.createElement('button');b.type='button';b.dataset.workspace=g.id;b.innerHTML='<span class="nav-icon">'+g.icon+'</span><span>'+g.label+'</span>';b.onclick=()=>{showTab(g.views[0]);closeSidebar()};nav.appendChild(b)}
const subLabel=document.createElement('div');subLabel.className='sidebar-section-label';subLabel.textContent='داخل القسم';sidebar.append(subLabel,tabs);
const footer=document.createElement('div');footer.className='sidebar-footer';sidebar.appendChild(footer);if($('logoutButton'))footer.appendChild($('logoutButton'));
const top=document.createElement('div');top.className='dashboard-topline';
const heading=document.createElement('div');heading.className='workspace-heading';heading.innerHTML='<h2 id="workspaceTitle">الآن</h2><p id="workspaceDescription">الحالة الحالية والتنبيهات التي تحتاج تدخل</p>';
const topActions=document.createElement('div');topActions.className='topline-actions';
const menu=document.createElement('button');menu.type='button';menu.className='secondary mobile-sidebar-toggle';menu.textContent='القائمة';menu.onclick=()=>document.body.classList.contains('sidebar-open')?closeSidebar():openSidebar();topActions.appendChild(menu);if($('syncStatus'))topActions.appendChild($('syncStatus'));top.append(heading,topActions);content.appendChild(top);
const filters=dashboard.querySelector('.filters');if(filters){filters.classList.add('admin-topbar');const fields=document.createElement('div');fields.className='filter-fields';for(const id of ['day','employeeFilter','queueFilter']){const n=$(id),o=n?.closest('label');if(o)fields.appendChild(o)}const adv=filters.querySelector('.filter-advanced');if(adv)fields.appendChild(adv);const actions=document.createElement('div');actions.className='filter-actions';const da=filters.querySelector('.date-actions');if(da)actions.appendChild(da);for(const id of ['resetFiltersButton','refreshButton'])if($(id))actions.appendChild($(id));const sr=document.createElement('div');sr.className='filter-summary-row';if($('filterSummary'))sr.appendChild($('filterSummary'));if($('periodNote')){$('periodNote').classList.add('period-note-compact');sr.appendChild($('periodNote'))}filters.prepend(fields);filters.append(actions,sr);content.appendChild(filters)}
if($('message'))content.appendChild($('message'));if($('operationsLoad')){$('operationsLoad').classList.add('operations-strip');content.appendChild($('operationsLoad'))}
const toolbar=dashboard.querySelector('.ops-toolbar');if(toolbar){const d=document.createElement('details');d.className='display-preferences';const s=document.createElement('summary');s.textContent='خيارات العرض وحفظ الفلاتر';d.append(s,toolbar);content.appendChild(d)}
for(const section of [...dashboard.querySelectorAll(':scope > .view')])content.appendChild(section);dashboard.append(sidebar,content);
function openSidebar(){document.body.classList.add('sidebar-open')}function closeSidebar(){document.body.classList.remove('sidebar-open')}backdrop.onclick=closeSidebar;window.addEventListener('resize',()=>{if(innerWidth>820)closeSidebar()});
for(const section of document.querySelectorAll('.view'))for(const p of [...section.children].filter(e=>e.tagName==='P'&&e.classList.contains('muted')&&!e.id&&e.textContent.trim().length>165)){if(p.closest('details'))continue;const d=document.createElement('details');d.className='help-detail';const s=document.createElement('summary');s.textContent='طريقة الحساب والتوضيح';p.before(d);d.append(s,p)}
const liveDetails=$('attentionDetails');if(liveDetails&&!liveDetails.closest('details')){const d=document.createElement('details');d.className='detail-panel';const s=document.createElement('summary');s.textContent='تفاصيل التنبيهات والإجراءات';liveDetails.before(d);d.append(s,liveDetails)}
for(const cards of document.querySelectorAll('.cards')){if(cards.dataset.compactReady)continue;cards.dataset.compactReady='1';cards.classList.add('summary-cards');const b=document.createElement('button');b.type='button';b.className='secondary indicators-toggle';b.textContent='باقي المؤشرات';cards.after(b);const sync=()=>b.hidden=cards.children.length<=6;new MutationObserver(sync).observe(cards,{childList:true});sync();b.onclick=()=>{const x=cards.classList.toggle('expanded');b.textContent=x?'اختصار المؤشرات':'باقي المؤشرات'}}
const collapsible={metricRows:'تفاصيل أداء الموظفين',callRows:'سجل المكالمات بالتفصيل',attendanceRows:'تفاصيل الحضور والبريك',shiftRows:'تفاصيل الخروج واستئناف العمل',queueRows:'تفاصيل مؤشرات أنواع الطلبات',missedRows:'قائمة المكالمات الفائتة',rosterRows:'قائمة الموظفين',reviewRows:'قائمة المتابعات',connectionRows:'تفاصيل الربط بالأجهزة',unattributedRows:'المكالمات غير المنسوبة',customerRows:'تكرار اتصالات العملاء'};
for(const [id,title] of Object.entries(collapsible)){const body=$(id),wrap=body?.closest('.tablewrap');if(!wrap||wrap.closest('details'))continue;const d=document.createElement('details');d.className='auto-detail';const s=document.createElement('summary');s.textContent=title;wrap.before(d);d.append(s,wrap)}
const baseShowTab=showTab;showTab=function(view){const group=groups.find(g=>g.views.includes(view))||groups[0];for(const b of nav.querySelectorAll('[data-workspace]')){const on=b.dataset.workspace===group.id;b.classList.toggle('selected',on);b.setAttribute('aria-current',on?'page':'false')}for(const b of tabs.querySelectorAll('[data-tab]'))b.hidden=!group.views.includes(b.dataset.tab);tabs.hidden=group.views.length===1;subLabel.hidden=group.views.length===1;$('workspaceTitle').textContent=group.title;$('workspaceDescription').textContent=group.desc;baseShowTab(view);closeSidebar()};
const expanded=new Set();function compactGroups(){const root=$('employeeLiveGroups');if(!root)return;for(const group of root.querySelectorAll('.employee-group')){if(group.dataset.compactApplied)continue;group.dataset.compactApplied='1';const items=[...group.querySelectorAll('.employee-tile')],state=[...group.classList].find(c=>c.startsWith('state-'))?.slice(6)||'';if(!['shift_ended','no_session'].includes(state)&&items.length<=8)continue;group.classList.add('employee-group-collapsible');const h=group.querySelector('h4'),b=document.createElement('button');if(!h)continue;b.type='button';b.className='secondary employee-group-toggle';const sync=()=>{const open=expanded.has(state);group.classList.toggle('employee-group-open',open);b.textContent=open?'إخفاء القائمة':'عرض القائمة'};b.onclick=()=>{expanded.has(state)?expanded.delete(state):expanded.add(state);sync()};h.appendChild(b);sync()}}
if($('employeeLiveGroups')){new MutationObserver(compactGroups).observe($('employeeLiveGroups'),{childList:true,subtree:true});compactGroups()}
const update=()=>document.body.classList.toggle('dashboard-active',!dashboard.hidden);new MutationObserver(update).observe(dashboard,{attributes:true,attributeFilter:['hidden']});update();
window.MarsadAdminUI={$,dashboard,tabs,groups,nav,topActions,subLabel,showBase:view=>showTab(view)};
showTab(document.querySelector('#tabs button.selected')?.dataset.tab||'live');
})();
