const API='https://marsad-kpi-live.karim87nu.chatgpt.site';
const $=id=>document.getElementById(id),today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),v=k=>p.find(x=>x.type===k).value,d=v('year')+'-'+v('month')+'-'+v('day');return Number(v('hour'))<9?new Date(Date.parse(d+'T12:00:00Z')-86400000).toISOString().slice(0,10):d};
let daily=null,historical=null,staff=[],context=null,contextCall=null,offset=0,lastLiveFetch=0,lastEmployeesFetch=0,refreshing=false,selectedTab='live',generation=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){if(v==null||!Number.isFinite(Number(v)))return 'غير معروف';const s=Math.max(0,Math.floor(Number(v)));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
const at=v=>v?new Date(v).toLocaleString('ar-EG',{timeZone:'Africa/Cairo'}):'—';
const averageSeconds=v=>v==null||!Number.isFinite(Number(v))?'غير متاح':Number(v).toFixed(2)+' ث';
const stateLabel=v=>({shift_ended:'خلص الشيفت — مستبعد',no_session:'لم يبدأ جلسة في نظامنا',unknown:'انقطاع رصد — آخر حالة تحتاج اتصال',offline:'خروج موثق',break:'بريك',on_call:'في مكالمة',ready:'متاح — بدون مكالمة حسب الرصد',post_call:'أنهى مكالمة؛ الاستقبال غير مثبت',logged_in:'دخول مسجل',uncertain:'حالة غير مؤكدة خلال التوقيت'}[v]||v||'غير معروف');
const eventLabel=v=>({shift_include:'ضم للمسؤولية من الإدارة',shift_exclude:'تأكيد نهاية الشيفت من الإدارة',session_login:'دخول / ربط الموظف',session_logout:'خروج الموظف',arabicss_logout:'خروج أرابيكس',arabicss_login:'دخول أرابيكس',break_start:'بداية بريك',break_end:'نهاية بريك',break_observed:'بريك قائم؛ البداية غير معروفة',break_end_unknown:'نهاية بريك؛ المدة ناقصة',call_observed:'مكالمة قائمة قبل الرصد',call_observed_end:'نهاية المكالمة المرصودة',page_closed:'انتقال / إغلاق الصفحة؛ ليس خروجًا مؤكدًا'}[v]||v);
const reasonLabel=v=>({work_resumed:'دخول لاحق مرتبط بنفس الموظف',linked_state_boundaries:'ربط الحالة بين دليلين في نفس الجلسة',admin_responsibility_included:'الإدارة ضمته للمسؤولية',admin_shift_excluded:'الإدارة أكدت نهاية الشيفت',explicit_logout:'خروج مؤكد',arabicss_logout:'خروج من أرابيكس',arabicss_login_page:'عودة إلى دخول أرابيكس',extension_changed:'تغير التحويلة',extension_restarted:'أعيد تشغيل الإضافة',tab_closed:'إغلاق صفحة الموظف',browser_restarted:'اكتُشف عند إعادة فتح المتصفح؛ وقت الإغلاق غير معروف',verified:'هوية موثقة',identity_verified:'تسجيل الهوية',bound:'ربط التحويلة',ready:'متصل',break:'بريك',recent_identity_event:'حدث حديث موثق',no_identity_events:'لا يوجد سجل هوية وقتها',missing_recent_presence:'لا توجد نبضة حديثة؛ لا يثبت الخروج',page_closed_or_unknown:'الصفحة أُغلقت أو الحالة غير مؤكدة',employee_created_later:'أُضيف الموظف بعد هذه المكالمة',changed_within_time_window:'تغيرت الحالة داخل توقيت المصدر',missing_call_time:'وقت الفائتة غير متاح',stale_logout:'دليل الخروج قديم'}[v]||v||'—');
const missedLabel=v=>({counted:'محتسبة (>7ث)',short_exempt:'معفاة — توضيح فقط',after_hours:'خارج ساعات العمل',unknown_wait:'انتظار غير معروف',unknown_queue:'نوع طلب غير معروف'}[v]||v);
const requestType=q=>({'0':'خارج ساعات العمل','1':'طلب أوردر','2':'متابعة أوردر','3':'شكاوى'}[String(q).slice(-1)]||'نوع طلب غير معروف');
const unavailable=e=>['break','on_call','offline'].includes(e.state);
const sourceClock=value=>String(value||'').replace(/\bAM\b/gi,'ص').replace(/\bPM\b/gi,'م');
function row(values,cls=''){return '<tr'+(cls?' class="'+cls+'"':'')+'>'+values.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>'}
function table(id,values,columns){$(id).innerHTML=values.join('')||'<tr><td colspan="'+columns+'">لا توجد بيانات مطابقة</td></tr>'}
function tableScope(id,list,cells){return globalThis.MarsadTables?.filterData(id,list,cells)||list}
const metricCells=p=>{const e=staff.find(e=>e.id===p.employeeId);return[e?.name||p.employee,e?.employeeCode||'—',p.calls,p.inbound,p.outbound,p.answered,p.answered?fmt(p.avgHandleTime):'غير متاح',at(p.firstLogin),at(p.lastLogout),fmt(p.breakSeconds),p.unknownBreaks,fmt((daily?.breakTotals||[]).find(x=>x.employeeId===p.employeeId)?.ongoingBreakSeconds||0),fmt((daily?.breakTotals||[]).find(x=>x.employeeId===p.employeeId)?.totalBreakSeconds??p.breakSeconds)]};
const callCells=e=>[e.agentName,e.extension,e.callType==='incoming'?'وارد':e.callType==='outgoing'?'صادر':'غير معروف',e.phone,(e.eventType==='agentunlinked'?(e.attributionSource==='history_session'?'مكتملة — مطابقة السجل مع هوية الموظف وتوقيت التحويلة':'مكتملة — الإضافة'):'بداية بدون نهاية — ليست دليلًا أنها جارية الآن')+(e.outsideHours?' — خارج فترة التشغيل':''),at(e.startedAt||e.occurredAt),e.eventType==='agentunlinked'?fmt(e.durationSeconds):'انظر المباشر'];
const queueCells=q=>[q.label,q.calls,q.answered,q.abandoned,averageSeconds(q.asa),q.sla==null?'غير متاح':Number(q.sla).toFixed(2)+'%',q.abandonmentRate==null?'غير متاح':Number(q.abandonmentRate).toFixed(2)+'%'];
function cards(id,values){$(id).innerHTML=values.map(([k,v])=>'<div class="card">'+esc(k)+'<span>'+esc(v)+'</span></div>').join('')}
function matches(e){return(!$('employeeFilter').value||Number(e.employeeId)===Number($('employeeFilter').value))&&(!$('extensionFilter').value||String(e.extension)===$('extensionFilter').value.trim())}
function callsFiltered(list=daily?.calls||[]){const q=$('callSearch').value.trim().toLowerCase();return tableScope('callRows',list.filter(e=>matches(e)&&(!q||(String(e.agentName)+' '+String(e.phone)).toLowerCase().includes(q))&&(!$('callType').value||e.callType===$('callType').value)&&(!$('callStatus').value||e.eventType===$('callStatus').value)),callCells)}
function eventsFiltered(list=daily?.timeline||[]){const f=$('eventFilter').value;return list.filter(e=>matches(e)&&(!f||f==='break'&&e.eventType.startsWith('break_')||f==='login'&&e.eventType.endsWith('_login')||f==='logout'&&e.eventType.endsWith('_logout')||f==='unknown'&&['page_closed','break_observed','break_end_unknown','call_observed','call_observed_end'].includes(e.eventType)))}
function queuesFiltered(){return tableScope('queueRows',(historical?.queues||[]).filter(q=>!$('queueFilter').value||q.queue===$('queueFilter').value),queueCells)}
function historyScope(){
 const h=historical?.report;if(!h||!$('queueFilter').value&&!globalThis.MarsadTables?.active('queueRows'))return h;
 const qs=queuesFiltered(),sum=k=>qs.reduce((n,q)=>n+(Number(q[k])||0),0),calls=sum('calls'),answered=sum('answered');
 const metricKnown=k=>qs.every(q=>!q.calls||q[k]!=null);
 return{...h,calls,answered,abandoned:sum('abandoned'),shortAbandoned:sum('shortAbandoned'),afterHours:sum('afterHours'),totalRecords:sum('totalRecords'),answeredWithinThreshold:sum('answeredWithinThreshold'),missingWaits:sum('missingWaits'),unknownStatuses:sum('unknownStatuses'),unclassifiedAbandoned:sum('unclassifiedAbandoned'),asa:answered&&qs.every(q=>!q.answered||q.asa!=null)?qs.reduce((n,q)=>n+(q.asa||0)*q.answered,0)/answered:null,sla:calls&&metricKnown('sla')?sum('answeredWithinThreshold')/calls*100:null,abandonmentRate:calls&&metricKnown('abandonmentRate')?sum('abandoned')/calls*100:null};
}
function filterSummary(){const employee=staff.find(e=>String(e.id)===$('employeeFilter').value)?.name,queue=$('queueFilter').value?requestType($('queueFilter').value):'كل أنواع الطلبات';if($('filterSummary'))$('filterSummary').textContent=[$('day').value,employee||'كل الموظفين',queue,$('extensionFilter').value?'تحويلة '+$('extensionFilter').value:''].filter(Boolean).join(' · ');}
function missedFiltered(){return(historical?.missed||[]).filter(c=>(!$('queueFilter').value||c.queue===$('queueFilter').value)&&(!$('missedFilter').value||c.classification===$('missedFilter').value))}
function contextDuration(e){if(e.elapsedSeconds==null)return '—';const min=fmt(e.elapsedSeconds),max=e.elapsedMaxSeconds==null?min:fmt(e.elapsedMaxSeconds);return(e.durationBasis==='observed_since'?'على الأقل ':'')+min+(context?.timeWindow?.precision==='minute'&&max!==min?' إلى '+max:'');}
function contextFiltered(list=context?.employees||[]){const f=$('contextFilter').value;return tableScope('contextRows',list.filter(e=>matches(e)&&(!f||f==='unavailable'&&unavailable(e)||f==='ready'&&e.state==='ready'||f==='excluded'&&e.state==='shift_ended'||f==='unknown'&&['unknown','uncertain'].includes(e.state))),e=>[e.name+' — '+e.code,stateLabel(e.state),e.extension||'—',contextDuration(e),shiftReason(e.reason),at(e.evidenceAt)])}
function dashboardQuery(date=$('day').value){return '/api/dashboard?'+new URLSearchParams({date,employee:$('employeeFilter').value,extension:$('extensionFilter').value.trim(),attendance:['attendance','metrics','profile'].includes(selectedTab)?'1':'0',...selectedTab==='live'?{live:'1'}:{},...['calls','attendance'].includes(selectedTab)?{all:'1'}:{}})}
const adminApiFlights=new Map();
async function api(path,options={}){
 const token=sessionStorage.getItem('adminPassword')||'',key=token+'|'+path,read=(options.method||'GET').toUpperCase()==='GET';
 if(read&&adminApiFlights.has(key))return adminApiFlights.get(key);
 const request=(async()=>{const r=await fetch(API+path,{...options,headers:{'x-admin-password':token,...(options.headers||{})},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(r.status===401?'كلمة المرور غير صحيحة أو انتهى الدخول':d.error||'تعذر الاتصال');return d;})();
 if(read)adminApiFlights.set(key,request);try{return await request}finally{if(read&&adminApiFlights.get(key)===request)adminApiFlights.delete(key)}
}
function showTab(id){selectedTab=id;$('filterNote').textContent=['queue','missed'].includes(id)?'فلتر الموظف يخص حالات الموظفين فقط. سجل أرابيكس بحساب مشترك لا يدعم نسبة المكالمة لشخص؛ استخدم نوع الطلب للسجل.':'فلتر الاسم ورقم التحويلة يطبق على بيانات الموظفين في القسم المفتوح.';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===id));if(['attendance','metrics','profile'].includes(id))refresh(true)}
function clearDay(){daily=null;historical=null;context=null;contextCall=null;$('contextPanel').hidden=true;renderDaily();renderHistory()}
async function refresh(force=false){
 if(!sessionStorage.getItem('adminPassword')||refreshing&&!force)return;
 refreshing=true;const date=$('day').value,dataScope=[date,$('employeeFilter').value,$('extensionFilter').value.trim()].join('|'),seq=++generation;
 try{
  // Operations views have their own combined, section-driven endpoint. Keep
  // this shared shell on the lightweight live snapshot there so we do not run
  // the same day-wide history attribution and session aggregation twice.
  const operationsViews=['intervention','analysis','followup','health','guide','unattributed','customers','reports','audit','adminUsers','alertLog','queue'];
  const liveOnly=selectedTab==='live'||operationsViews.includes(selectedTab);
  const [d,h,employees]=await Promise.all([api(dashboardQuery(date)),api('/api/history?date='+date+(liveOnly?'&live=1':'')),staff.length&&(!force&&Date.now()-lastEmployeesFetch<60000)?Promise.resolve(null):api('/api/employees')]);
  if(seq!==generation||date!==$('day').value)return;
  $('day').max=d.today;d.adminClientScope=dataScope;daily=d;historical=h;if(employees){staff=[...employees.employees,...(employees.archivedEmployees||[])];lastEmployeesFetch=Date.now()}offset=Date.parse(d.serverNow)-Date.now();lastLiveFetch=Date.now();
  const choice=$('employeeFilter').value,employeeOptions='<option value="">كل الموظفين</option>'+staff.map(e=>'<option value="'+e.id+'">'+esc(e.name+(e.active?'':' — محذوف'))+'</option>').join('');if($('employeeFilter').innerHTML!==employeeOptions)$('employeeFilter').innerHTML=employeeOptions;$('employeeFilter').value=choice;
  const queueChoice=$('queueFilter').value,queueOptions='<option value="">كل أنواع الطلبات</option>'+(h.queues||[]).map(q=>'<option value="'+esc(q.queue)+'">'+esc(q.label)+'</option>').join('');if($('queueFilter').innerHTML!==queueOptions)$('queueFilter').innerHTML=queueOptions;$('queueFilter').value=queueChoice;
  $('syncStatus').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-EG',{timeZone:'Africa/Cairo'});$('syncStatus').classList.remove('bad');$('message').textContent='';
  $('periodNote').textContent='يوم البيانات: '+date+' من 9ص حتى قبل 9ص اليوم التالي. التشغيل 9ص–3ص؛ الفترة 3ص–8:59ص خارج ساعات العمل ومحفوظة ضمن نفس اليوم. المباشر يعرض الآن.';
  if(!liveOnly){renderDaily();renderHistory()}renderRoster();renderLive();filterSummary();window.dispatchEvent(new Event('kpi-admin-refresh'));
 }catch(e){if(seq===generation){$('syncStatus').textContent='تعذر التحديث — البيانات المعروضة قديمة';$('syncStatus').classList.add('bad');$('message').textContent=e.message;renderLive()}}finally{if(seq===generation)refreshing=false}
}
function metricsFiltered(){const perf=daily?.performance||[];const records=$('extensionFilter').value?perf:staff.filter(e=>e.active||perf.some(p=>p.employeeId===e.id)||Number($('employeeFilter').value)===e.id).map(e=>perf.find(p=>p.employeeId===e.id)||{employeeId:e.id,employee:e.name,calls:0,inbound:0,outbound:0,answered:0,avgHandleTime:0,breakSeconds:0,unknownBreaks:0,firstLogin:null,lastLogout:null});return tableScope('metricRows',records.filter(p=>!$('employeeFilter').value||p.employeeId===Number($('employeeFilter').value)),metricCells)}
const liveLabel=s=>({shift_ended:'خلص الشيفت — مستبعد',ready:'متاح — منتظر مكالمة',on_call:'شغال — في مكالمة',break:'في بريك',logged_in:'بانتظار دخول التشغيل',offline:'خروج موثق',no_session:'لم يسجل دخولًا',unknown:'انقطاع رصد'}[s]||'انقطاع رصد');
function liveState(p){
 const age=Date.now()+offset-Date.parse(p.evidenceAt||'');
 if(Date.now()-lastLiveFetch>=15000)return 'unknown';
 if(['offline','no_session','shift_ended'].includes(p.state))return p.state;
 if(!Number.isFinite(age)||age < -5000||age>=90000)return 'unknown';
 if(p.state==='ready')return /^\d+$/.test(String(p.extension||''))?'ready':'logged_in';
 return ['on_call','break','logged_in'].includes(p.state)?p.state:'unknown';
}
function livePeople(){const now=Date.now()+offset,list=tableScope('liveRows',(daily?.presence||[]).filter(matches).filter(p=>!$('liveStateFilter').value||liveState(p)===$('liveStateFilter').value),p=>[staff.find(e=>e.id===p.employeeId)?.name||'اسم غير متاح',p.extension,liveLabel(liveState(p)),p.phone||'—',p.queue?requestType(p.queue):'—',at(p.startedAt),['on_call','break'].includes(liveState(p))&&p.startedAt?fmt((now-Date.parse(p.startedAt))/1000):'غير معروف',at(p.evidenceAt)]);return globalThis.MarsadLiveDetails?globalThis.MarsadLiveDetails(list):list}
function renderDaily(){
 const perf=metricsFiltered(),sum=k=>perf.reduce((n,p)=>n+(p[k]||0),0);
 const ongoing=perf.reduce((n,p)=>n+((daily?.breakTotals||[]).find(x=>x.employeeId===p.employeeId)?.ongoingBreakSeconds||0),0);
 cards('metricCards',[['مكالمات مسجلة',sum('calls')],['وارد',sum('inbound')],['صادر',sum('outbound')],['البريك المكتمل',fmt(sum('breakSeconds'))],['بريك جارٍ مرصود',fmt(ongoing)],['إجمالي البريك — المكتمل والجاري',fmt(sum('breakSeconds')+ongoing)]]);
 table('metricRows',perf.map(p=>row(metricCells(p))),13);
 table('callRows',callsFiltered().map(e=>row(callCells(e))),7);
 renderAttribution();
 renderAttendanceDurations();
 $('callCoverage').textContent=daily?.detailsTruncated?'التفاصيل تعرض آخر 300 مكالمة؛ التصدير يسحب اليوم كاملًا قبل تطبيق الفلاتر.':'كل المكالمات المسجلة لهذا اليوم ظاهرة حسب الفلاتر.';
 renderContext();
 renderShifts();
}
const attributionReason=v=>({same_owner_boundaries:'نفس الموظف استخدم التحويلة قبل المكالمة وبعدها',after_owner_handover:'إسناد حسب قاعدة التسليم: أول موظف موثّق استخدم التحويلة بعدها',observed_owner:'الموظف محدد من المكالمات المسجلة؛ لا نكرر العد',matching_limit:'بيانات متداخلة كثيرة — المطابقة غير محسومة',session_at_call:'مطابقة التحويلة مع جلسة الموظف وقت المكالمة',already_observed:'مسجلة بالإضافة — لا تُضاف مرة ثانية',possible_duplicate:'تطابق محتمل مع الإضافة — لم نكرر العد',unverified_extension:'رقم أرابيكس لم تثبت مطابقته للتحويلة',uncertain_time:'التوقيت ناقص أو غير مؤكد',identical_source_rows:'صفوف متطابقة بلا رقم مكالمة يميزها',missing_duration:'مدة المكالمة غير متاحة',ambiguous_session:'أكثر من جلسة محتملة وقت المكالمة',no_session_at_call:'لا توجد جلسة تغطي توقيت المكالمة',missing_identity:'اسم الموظف غير محفوظ',not_answered:'ليست مكالمة تم الرد عليها — لا تُنسب لموظف'}[v]||v);
function renderAttribution(){const a=daily?.historyAttribution;$('attributionNote').textContent=a?'استُكملت '+a.summary.recovered+' مكالمة من السجل، و'+a.summary.alreadyObserved+' مسجلة بالإضافة بدون تكرار. '+a.summary.unattributedAnswered+' مكالمة مردود عليها لم تُنسب بأمان. الأعداد تخص اليوم كاملًا؛ الجدول يخضع لفلتر الموظف والتحويلة. عدم النسبة لا يعني خطأ الموظف.':'لا يوجد سحب سجل متاح للمطابقة بعد.';table('attributionRows',(a?.rows||[]).map(x=>row([x.date+' '+x.start,x.phone,x.accountId,x.employeeName||'غير منسوبة',attributionReason(x.reason)])),5)}
function sessionSeconds(s,day=false){const now=Date.now()+offset,fresh=Date.now()-lastLiveFetch<15000&&now-s.lastSeen<90000,start=s.workStartedAt??s.issuedAt;if(s.workStartedAt===null)return 0;return s.running&&fresh?Math.max(0,Math.floor(((day?Math.min(now,s.dayEnd):now)-(day?Math.max(start,s.dayStart):start))/1000)):day?s.daySeconds:s.durationSeconds}
function eventDuration(e,source=daily){const d=(source?.durations||[]).find(d=>d.eventId===e.id);if(d?.durationSeconds!=null)return (d.durationKind==='session'?'مدة الجلسة: ':'')+fmt(d.durationSeconds)+(d.complete?'':' — رصد ناقص');return e.eventType==='break_end'?fmt(e.durationSeconds):d?.durationKind==='transition'?'حدث لحظي':d?.durationKind==='unknown'||e.eventType==='break_end_unknown'?'غير معروفة':'غير معروفة / انظر مدد الجلسات والحالات'}
const operationLabel=v=>({session:'جلسة عمل — دخول وخروج',break:'بريك',break_unconfirmed:'بريك مرصود بلا طرفي المدة',ready:'متاح بدون مكالمة',on_call:'في مكالمة',post_call:'بعد المكالمة',logged_in:'بانتظار دخول التشغيل',unknown:'انقطاع رصد',offline:'بعد نهاية الشيفت — توضيح فقط'}[v]||stateLabel(v));
function attendanceOperations(source=daily){
 const a=source?.attendance;if(!a)return[];const now=Date.now()+offset,fresh=source===daily&&Date.now()-lastLiveFetch<15000,seen=new Set();
 const sessions=(a.sessions||[]).filter(s=>{if(seen.has(s.id))return false;seen.add(s.id);return true}).map(s=>({...s,operation:'session',startedAt:new Date(Math.max(s.workStartedAt??s.issuedAt,s.dayStart)).toISOString(),endedAt:s.running?null:s.endedAt||s.observedThrough,seconds:source===daily?sessionSeconds(s,true):s.daySeconds,accuracy:s.workStartedAt===null?'تسجيل هوية فقط — لم يبدأ العمل':(s.running?'جارية حسب آخر دليل':s.durationComplete?'مكتملة':'النهاية غير مؤكدة — حتى آخر رصد')+(s.identityDelaySeconds?' · انتظار الجاهزية '+fmt(s.identityDelaySeconds)+' — منفصل عن العمل':'')}));
 // State spans are non-overlapping intervals, not copies of start/end events.
 const breaks=(source.completedBreaks||[]).filter(s=>{const k=['break',s.employeeId,s.extension,s.startedAt,s.endedAt].join('|');if(seen.has(k))return false;seen.add(k);return true;});
 const observed=[];for(const s of (a.states||[])){let pieces=[[Date.parse(s.startedAt),Date.parse(s.endedAt)]];for(const b of breaks.filter(b=>b.employeeId===s.employeeId&&b.extension===s.extension)){const x=Date.parse(b.startedAt),y=Date.parse(b.endedAt);pieces=pieces.flatMap(([a,z])=>y<=a||x>=z?[[a,z]]:[[a,Math.min(z,x)],[Math.max(a,y),z]].filter(([p,q])=>q>p));}for(const [x,y]of pieces)observed.push({...s,startedAt:new Date(x).toISOString(),endedAt:new Date(y).toISOString(),durationSeconds:Math.floor((y-x)/1000),running:s.running&&y===Date.parse(s.endedAt)});}
 const spans=[];for(const s of [...observed,...breaks].sort((x,y)=>x.employeeId-y.employeeId||String(x.extension).localeCompare(String(y.extension))||Date.parse(x.startedAt)-Date.parse(y.startedAt))){const key=[s.employeeId,s.extension,s.state,s.startedAt,s.endedAt].join('|');if(seen.has('state|'+key))continue;seen.add('state|'+key);const previous=spans.at(-1);if(previous&&previous.employeeId===s.employeeId&&previous.extension===s.extension&&previous.state===s.state&&previous.endedAt===s.startedAt&&s.state!=='break'){previous.endedAt=s.endedAt;previous.durationSeconds+=s.durationSeconds;previous.running=s.running;previous.evidenceUntil=s.evidenceUntil;}else spans.push({...s});}
 return tableScope('attendanceRows',[...sessions,...spans.map(s=>({...s,operation:s.state,seconds:s.durationSeconds+(s.running&&fresh?Math.max(0,Math.floor((Math.min(now,s.evidenceUntil)-Date.parse(s.endedAt))/1000)):0),accuracy:['unknown','break_unconfirmed'].includes(s.state)?'لا يوجد دليل كافٍ — غير مضاف لإجمالي البريك':s.state==='offline'?'توضيح فقط — ليس تقصيرًا':s.running?'جارية حسب آخر دليل':'فترة مرصودة',endedAt:s.running?null:s.endedAt}))].filter(matches).filter(s=>!$('eventFilter').value||s.operation===$('eventFilter').value).sort((x,y)=>Date.parse(y.startedAt)-Date.parse(x.startedAt)),s=>[staff.find(e=>e.id===s.employeeId)?.name||'اسم غير متاح',s.extension,operationLabel(s.operation),at(s.startedAt),s.endedAt?at(s.endedAt):'جارية',fmt(s.seconds),s.accuracy]);
}
function renderAttendanceDurations(){const list=attendanceOperations(),name=s=>staff.find(e=>e.id===s.employeeId)?.name||'اسم غير متاح';table('attendanceRows',list.map(s=>row([name(s),s.extension,operationLabel(s.operation),at(s.startedAt),s.endedAt?at(s.endedAt):'جارية',fmt(s.seconds),s.accuracy])),7);$('attendanceCoverage').textContent=list.length+' عملية حسب الفلاتر. المدة تخص اليوم المختار؛ الجلسة تشمل حالات الموظف ولا تُجمع مرة أخرى مع البريكات والحالات.';}
function renderLive(preserveGroups=false){
 const fresh=Date.now()-lastLiveFetch<15000,people=livePeople(),now=Date.now()+offset;
 const count=s=>fresh?people.filter(p=>liveState(p)===s).length:'غير مؤكد';
 cards('liveCards',[['المتاحون لاستقبال مكالمة',count('ready')],['شغالون في مكالمات',count('on_call')],['في بريك',count('break')],['بانتظار دخول التشغيل',count('logged_in')],['خروج / لم يسجل',fresh?people.filter(p=>['offline','no_session'].includes(liveState(p))).length:'غير مؤكد'],['خلصوا الشيفت — مستبعدون',count('shift_ended')],['انقطاع رصد',people.filter(p=>liveState(p)==='unknown').length]]);
 const shown=livePeople(),duration=p=>['on_call','break'].includes(liveState(p))&&p.startedAt?fmt((now-Date.parse(p.startedAt))/1000):'غير معروف';
 if(!preserveGroups)$('employeeLiveGroups').innerHTML=['ready','on_call','break','logged_in','unknown','offline','no_session','shift_ended'].filter(s=>!$('liveStateFilter').value||$('liveStateFilter').value===s).map(s=>{
  const list=shown.filter(p=>liveState(p)===s);if(!list.length&&!['ready','on_call','break'].includes(s))return '';
  return '<section class="employee-group state-'+s+'"><h4>'+esc(liveLabel(s))+' <span>'+list.length+'</span></h4><div class="employee-tiles">'+(list.map(p=>'<article class="employee-tile"><strong>'+esc(staff.find(e=>e.id===p.employeeId)?.name||'اسم الموظف غير متاح')+'</strong><span>'+esc(liveLabel(s))+'</span>'+(['on_call','break'].includes(s)?'<time class="clock">'+esc(duration(p))+'</time>':'')+'</article>').join('')||'<p class="muted">لا يوجد موظفون بهذه الحالة</p>')+'</div></section>';
 }).join('')||'<p class="muted">لا يوجد موظفون مطابقون للفلاتر.</p>';
 $('liveRows').innerHTML=shown.map(p=>{const e=staff.find(e=>e.id===p.employeeId);return '<tr>'+[e?.name||'اسم غير متاح',p.extension,liveLabel(liveState(p)),p.phone||'—',p.queue?requestType(p.queue):'—',at(p.startedAt)].map(v=>'<td>'+esc(v)+'</td>').join('')+'<td><span class="clock">'+esc(duration(p))+'</span></td><td>'+esc(at(p.evidenceAt))+'</td></tr>'}).join('')||'<tr><td colspan="8">لا يوجد موظفون مطابقون للفلاتر</td></tr>';
 const live=historical?.live,stale=!fresh||!live||Date.now()-Date.parse(live.observedAt)>30000;
 const records=(live?.records||[]).filter(r=>!$('queueFilter').value||r[0]===$('queueFilter').value),waiting=records.filter(r=>/^on wait$|^waiting$/i.test(String(r[10]).trim()));
 $('queueLiveNote').textContent=(live?(stale?'بيانات قديمة — لا تؤكد الانتظار الآن':'منتظرون الآن: '+waiting.length)+' — آخر سحب '+at(live.observedAt):'الانتظار غير متاح — راجع اتصال موصل الإدارة.')+' · هذا قسم العملاء، وليس الموظفين المتاحين؛ لا يتفلتر باسم الموظف.';
 table('waitingRows',waiting.map(r=>row([requestType(r[0]),r[9],r[8]])),3);
 table('queueLiveRows',records.map(r=>row([requestType(r[0]),r[2],r[9],r[8],/^live call$/i.test(String(r[10]).trim())?'مكالمة جارية':/^on wait$|^waiting$/i.test(String(r[10]).trim())?'ينتظر الرد':r[10]])),5);
 const alerts=[];
 if(!fresh)alerts.push('بيانات الموظفين قديمة — المتاحون الآن غير مؤكدين');
 if(stale)alerts.push('انتظار العملاء غير مؤكد — لا توجد لقطة حديثة');
 if(!stale&&waiting.some(r=>{const t=String(r[8]).trim();return /^\d+:[0-5]\d:[0-5]\d$/.test(t)&&t.split(':').reduce((v,n)=>v*60+Number(n),0)>7}))alerts.push('فيه عملاء انتظارهم تجاوز 7 ثوانٍ');
 const overBreak=people.filter(p=>liveState(p)==='break'&&p.startedAt&&now-Date.parse(p.startedAt)>=900000);
 const overCall=people.filter(p=>liveState(p)==='on_call'&&p.startedAt&&now-Date.parse(p.startedAt)>240000);
 if(overBreak.length)alerts.push(overBreak.length+' موظف تجاوز بريك 15 دقيقة');if(overCall.length)alerts.push(overCall.length+' مكالمة تجاوزت 4 دقائق');
 $('attentionNow').textContent=alerts.length?alerts.join(' · '):'لا توجد تنبيهات تأخير في البيانات الحالية';$('attentionNow').classList.toggle('warning',!!alerts.length);
 const h=historyScope();
 cards('overviewDayCards',h?[['مكالمات يوم التشغيل',h.calls],['تم الرد',h.answered],['فائتة محتسبة',h.abandoned],['الرد خلال 10ث',h.sla==null?'غير متاح':Number(h.sla).toFixed(2)+'%']]:[['مؤشرات اليوم','لا يوجد سجل محفوظ']]);
 $('overviewDayNote').textContent='يوم التشغيل '+($('day').value||'—')+' من 9ص إلى 3ص اليوم التالي. '+(h?'سجل '+($('queueFilter').value?requestType($('queueFilter').value):'كل أنواع الطلبات')+'؛ ليس إجمالي الموظف المحدد.':'استكمل سحب السجل من قسم مؤشرات المكالمات.');
}
function renderHistory(){
 const h=historyScope();
 let notice=$('missedSourceStatus');if(!notice){notice=document.createElement('p');notice.id='missedSourceStatus';notice.className='source-note';$('missedRows').closest('.tablewrap').before(notice)}
 notice.textContent=h?'آخر وصول لسجل المكالمات: '+at(h.importedAt)+'. الفائتة تظهر بعد وصول سجل أرابيكس؛ اختفاء العميل من الانتظار وحده لا يثبت أنها فائتة.':'لم يصل سجل لهذا اليوم بعد؛ غياب الصفوف لا يعني عدم وجود فائتة.';
 if(h&&$('day').value===today()&&Date.now()-Date.parse(h.importedAt)>360000)notice.textContent+=' تنبيه: السجل لم يتحدث منذ أكثر من 6 دقائق؛ راجع جهاز التجميع واتصال أرابيكس.';
 $('historyCoverage').textContent=h?'يوم التشغيل '+h.date+' — آخر سحب '+at(h.importedAt)+' — '+(h.verifiedTotal?'عدد الصفوف مطابق لإجمالي المصدر حتى وقت السحب':'ملف مستورد؛ اكتمال اليوم غير مثبت'):'لا يوجد سجل أرابيكس محفوظ لهذا التاريخ.';if(h?.missingCalendarDates?.length)$('historyCoverage').textContent+=' — تنبيه: سجل أرابيكس غير متوفر للتاريخ '+h.missingCalendarDates.join('، ')+'؛ بيانات الفترة غير مكتملة حتى استكمال السحب.';
 const qs=queuesFiltered(),perc=v=>v==null?'غير متاح':Number(v).toFixed(2)+'%';
 cards('historyCards',h?[['مكالمات محتسبة',h.calls],['تم الرد',h.answered],['فائتة محتسبة',h.abandoned],['≤7ث للتوضيح',h.shortAbandoned],['متوسط انتظار الرد',averageSeconds(h.asa)],['الرد خلال 10 ثوانٍ',perc(h.sla)],['نسبة المكالمات الفائتة',perc(h.abandonmentRate)],['خارج ساعات العمل',h.afterHours]]:[]);
 table('queueRows',qs.map(q=>row([q.label,q.calls,q.answered,q.abandoned,averageSeconds(q.asa),perc(q.sla),perc(q.abandonmentRate)])),7);
 if($('calculationNote'))$('calculationNote').textContent=h?'النطاق: '+($('queueFilter').value?requestType($('queueFilter').value):'كل أنواع الطلبات')+' · '+h.totalRecords+' صف في السجل · '+h.calls+' مكالمة محتسبة = '+h.answered+' تم الرد + '+h.abandoned+' فائتة محتسبة'+(h.unknownStatuses||h.unclassifiedAbandoned?' + حالات غير مصنفة':'')+' · نسبة الرد خلال 10 ثوانٍ: '+h.answeredWithinThreshold+' ÷ '+h.calls+' · متوسط انتظار الرد: مجموع انتظار المكالمات المردود عليها ÷ '+h.answered+'. فلتر الموظف لا يغيّر إجمالي خدمة أرابيكس.':'لا توجد بيانات لحساب النسب.';
 $('missedRows').innerHTML=missedFiltered().map(c=>'<tr>'+[c.queueLabel,c.date+' '+sourceClock(c.end||((c.start||'غير معروف')+' — بداية السجل؛ النهاية غير مسجلة')),c.phone,fmt(c.waitSeconds),missedLabel(c.classification)].map(v=>'<td>'+esc(v)+'</td>').join('')+'<td><button data-missed="'+c.index+'" class="secondary">من لم يكن متاحًا؟</button></td></tr>').join('')||'<tr><td colspan="6">لا توجد فائتة مطابقة لهذا اليوم</td></tr>';
}
function renderContext(){
 if(!context)return;
 const contextTable=$('contextRows').closest?.('table');if(contextTable){const header=contextTable.querySelector('thead tr');header.innerHTML=['الموظف','الحالة عند دخول الطابور','أصبح متاحًا أثناء الانتظار','دليل الرنين','الحالة عند نهاية الانتظار','التحويلة','المدة','التفسير'].map(x=>'<th>'+esc(x)+'</th>').join('')}
 const list=contextFiltered();
 cards('contextCounts',[['متاح — بدون مكالمة',list.filter(e=>e.state==='ready').length],['بريك',list.filter(e=>e.state==='break').length],['في مكالمة',list.filter(e=>e.state==='on_call').length],['خروج ضمن المسؤولية',list.filter(e=>e.state==='offline').length],['خلص الشيفت — مستبعد',list.filter(e=>e.state==='shift_ended').length],['انقطاع أو تغير الحالة',list.filter(e=>['unknown','uncertain'].includes(e.state)).length]]);
 table('contextRows',list.sort((a,b)=>Number(unavailable(b))-Number(unavailable(a))).map(e=>row([e.name+' — '+e.code,stateLabel(e.queueEntryState),e.becameReadyDuringWait?'أصبح متاحًا أثناء الانتظار'+(e.readyDuringWaitAt?' — '+at(e.readyDuringWaitAt):''):'—',e.ringResult==='proved'?'ثبت الرنين':'لا يوجد دليل رنين مسجل',stateLabel(e.state),e.extension||'—',contextDuration(e),shiftReason(e.reason)],unavailable(e)?'unavailable':'')),8);
}
const shiftReason=v=>({logout_shift_ended:'خروج مسجل — نهاية شيفت تلقائية',admin_responsibility_included:'الإدارة ضمته للمسؤولية',admin_shift_excluded:'الإدارة أكدت الاستبعاد',closure_uncertain:'انقطاع / انتهاء صلاحية؛ ليس نهاية شيفت مؤكدة'}[v]||reasonLabel(v));
function shiftsFiltered(){return(daily?.shifts||[]).filter(s=>matches(s))}
function renderShifts(){table('shiftRows',shiftsFiltered().map(s=>'<tr>'+[staff.find(e=>e.id===s.employeeId)?.name||'اسم غير متاح',at(s.issuedAt),at(s.revokedAt),s.continued?'استأنف العمل — ليست نهاية شيفت':s.excluded?'خرج — الشيفت منتهٍ حاليًا':'ضمن المسؤولية — انقطاع رصد',shiftReason(s.reason)+(s.note?' — '+s.note:'')].map(v=>'<td>'+esc(v)+'</td>').join('')+(s.continued?'<td>استئناف '+esc(at(s.resumedAt))+'</td></tr>':'<td><button class="secondary" data-shift="'+esc(s.id)+'" data-shift-action="'+(s.excluded?'include':'exclude')+'">'+(s.excluded?'ضم للمسؤولية':'تأكيد نهاية الشيفت')+'</button></td></tr>')),6)}
async function changeShift(sessionId,action){const s=shiftsFiltered().find(s=>s.id===sessionId);if(!s)return;const note=prompt(action==='include'?'سبب ضم الموظف للمسؤولية بعد خروجه:':'سبب تأكيد نهاية الشيفت:');if(!note?.trim())return;if(!confirm('سيُعاد تفسير حالات المكالمات من وقت خروج هذه الجلسة حتى الدخول التالي، مع حفظ السبب. تأكيد؟'))return;try{await api('/api/shifts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employeeId:s.employeeId,sessionId:s.id,action,requestId:crypto.randomUUID(),note:note.trim()})});await refresh(true);if(contextCall){context=null;$('contextPanel').hidden=true}$('shiftMessage').textContent='تم الحفظ؛ افتح تفاصيل المكالمة مجددًا لعرض التحديث'}catch(e){$('shiftMessage').textContent='لم يُحفظ التغيير: '+e.message}}
async function showContext(index){
 const reportId=historical?.report?.id;if(!reportId)return;
 $('contextPanel').hidden=false;$('contextNote').textContent='جارٍ مراجعة سجل الحالات…';context=null;table('contextRows',[],6);
 try{const d=await api('/api/history?reportId='+reportId+'&date='+$('day').value+'&missedIndex='+index);if(historical?.report?.id!==reportId)return;context=d.context;contextCall=d.call;
 $('contextTitle').textContent=d.call.date+' — '+sourceClock(d.call.end||d.call.start||'وقت غير معروف')+' — '+d.call.phone;
 $('contextNote').textContent=(d.context.queueEntryWindow?'بداية الانتظار المقدرة: '+sourceClock(d.context.queueEntryWindow.start)+'؛ نهاية الانتظار: '+sourceClock(d.context.timeWindow?.end||'')+'. ':'وقت دخول الطابور غير متاح من السجل. ')+(d.context.timeWindow?.precision==='minute'?'التوقيت بالدقيقة؛ تغير الحالة داخل الفترة يظهر غير محسوم. ':'')+'حالة الدخول مبنية على آخر رصد حديث، والجاهزية أثناء الانتظار تظهر منفصلة. الرنين على التحويلة لا يثبت إلا بحدث رنين صريح؛ هذا الدليل غير مسجل حاليًا في المصدر.';
 renderContext();$('contextPanel').scrollIntoView({behavior:'smooth',block:'start'});
 }catch(e){$('contextNote').textContent='تعذر تحديد الحالات: '+e.message}
}
function renderRoster(){ $('rosterRows').innerHTML=staff.filter(e=>!e.historyOnly&&(!$('employeeFilter').value||e.id===Number($('employeeFilter').value))).map(e=>'<tr>'+[e.name,e.employeeCode,e.active?'نشط':'محذوف من الدخول'].map(v=>'<td>'+esc(v)+'</td>').join('')+'<td><button class="secondary" data-employee="'+e.id+'">'+(e.active?'تعطيل الدخول':'استعادة')+'</button> <button class="secondary" data-pin="'+e.id+'">تعديل الباسورد</button> <button class="secondary" data-delete="'+e.id+'">حذف نهائي</button></td></tr>').join('')}
async function changeEmployee(id){const e=staff.find(e=>e.id===id);if(!e)return;if(e.active&&!confirm('حذف الموظف من تسجيل الدخول وإنهاء جلساته؟ السجل سيظل محفوظًا.'))return;try{await api('/api/employees',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,active:!e.active})});await refresh(true);$('employeeMessage').textContent='تم حفظ التغيير'}catch(err){$('employeeMessage').textContent=err.message}}
let pinEmployee=null;
const passwordError=e=>({password_in_use:'الباسورد مستخدم لموظف آخر؛ اختار باسورد مختلف',password_confirmation_mismatch:'تأكيد الباسورد غير مطابق',password_migration_required:'تعذر التحقق من الباسوردات القديمة؛ لم يتم حفظ التغيير',employee_code_exists:'كود الموظف موجود بالفعل'}[e.message]||e.message);
function editPin(id){const e=staff.find(x=>x.id===id&&!x.historyOnly);if(!e)return;pinEmployee=id;$('pinEditor').hidden=false;$('pinEmployeeName').textContent='تعديل باسورد '+e.name;$('newPin').value=$('newPinConfirm').value='';$('newPin').focus();$('pinEditor').scrollIntoView({block:'center'})}
async function savePin(){const id=pinEmployee,pin=$('newPin').value,pinConfirmation=$('newPinConfirm').value;if(!id||!/^\d+$/.test(pin)){$('employeeMessage').textContent='اكتب باسورد أرقام؛ بدون طول محدد';return}if(pin!==pinConfirmation){$('employeeMessage').textContent='تأكيد الباسورد غير مطابق';return}if(!confirm('تغيير الباسورد ينهي جلسة الموظف الحالية ويطلب دخوله مجددًا. حفظ؟'))return;$('savePinButton').disabled=true;try{await api('/api/employees',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,pin,pinConfirmation})});$('newPin').value=$('newPinConfirm').value='';$('pinEditor').hidden=true;pinEmployee=null;await refresh(true);$('employeeMessage').textContent='تم تغيير الباسورد وإنهاء الجلسة السابقة'}catch(e){$('employeeMessage').textContent='لم يتغير الباسورد: '+passwordError(e)}finally{$('savePinButton').disabled=false}}
async function deleteEmployee(id){const e=staff.find(x=>x.id===id&&!x.historyOnly);if(!e)return;const confirmCode=prompt('حذف حساب '+e.name+' نهائيًا وإنهاء جلساته. لا يمكن استعادة الحساب؛ المكالمات والبريكات السابقة تظل محفوظة. يُحذف سجل وصول تنبيهات هذا الحساب أيضًا. اكتب كود الموظف للتأكيد: '+e.employeeCode);if(confirmCode===null)return;if(confirmCode!==e.employeeCode){$('employeeMessage').textContent='الكود غير مطابق؛ لم يتم الحذف';return}try{await api('/api/employees',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id,confirmCode})});if(pinEmployee===id){$('newPin').value='';$('pinEditor').hidden=true;pinEmployee=null}if($('employeeFilter').value===String(id))$('employeeFilter').value='';context=null;$('contextPanel').hidden=true;await refresh(true);$('employeeMessage').textContent='تم حذف حساب الموظف نهائيًا؛ سجل المكالمات والبريكات محفوظ'}catch(err){$('employeeMessage').textContent='لم يتم الحذف: '+err.message}}
async function addEmployee(){
 const name=$('empName').value.trim(),employeeCode=$('empCode').value.trim(),pin=$('empPin').value,pinConfirmation=$('empPinConfirm').value;
 if(!name||!employeeCode||!/^\d+$/.test(pin)){$('employeeMessage').textContent='اكتب الاسم والكود وباسورد أرقام؛ بدون طول محدد';return}
 if(pin!==pinConfirmation){$('employeeMessage').textContent='تأكيد الباسورد غير مطابق';return}
 try{const records=(await api('/api/employees')).employees,old=records.find(e=>e.employeeCode===employeeCode);
 if(old&&(old.name!==name||old.active))throw Error('الكود موجود باسم '+old.name+(old.active?' والموظف نشط بالفعل':'؛ استخدم نفس الاسم لاستعادته'));
 await api('/api/employees',{method:old?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(old?{id:old.id,active:true,pin,pinConfirmation}:{name,employeeCode,pin,pinConfirmation})});
 $('empName').value=$('empCode').value=$('empPin').value=$('empPinConfirm').value='';await refresh(true);$('employeeMessage').textContent=old?'تمت الاستعادة وتحديث الباسورد':'تمت إضافة الموظف؛ الدخول بباسورده عبر الإضافة 2.5.2 أو أحدث';
 }catch(e){$('employeeMessage').textContent=passwordError(e)}
}
function csv(name,head,rows){const url=URL.createObjectURL(MarsadExcel.build(head,rows));const a=document.createElement('a');a.href=url;a.download=name.replace(/\.(csv|xlsx)$/i,'')+'-'+(['live-snapshot','queue-live'].includes(name)?today():$('day').value)+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const contextHeaders=['تاريخ المكالمة','وقت المصدر','الهاتف','نوع الطلب','الموظف','الكود','الحالة عند دخول الطابور','أصبح متاحًا أثناء الانتظار','دليل الرنين على التحويلة','الحالة عند نهاية الانتظار','التحويلة','مدة الحالة بالثواني وقت الفائتة','بداية الحالة','دقة المدة','السبب','آخر دليل','مرجع التوقيت'];
function contextLines(call,c){return contextFiltered(c.employees).map(e=>[call.date,call.end||call.start,call.phone,requestType(call.queue),e.name,e.code,stateLabel(e.queueEntryState),e.becameReadyDuringWait?'نعم — '+(e.readyDuringWaitAt||'وقت غير محدد'):'لا يوجد رصد',e.ringResult==='proved'?'مثبت':'غير مسجل',stateLabel(e.state),e.extension,e.elapsedSeconds,e.stateStartedAt,e.durationBasis==='recorded_start'?'من البداية المسجلة':e.durationBasis==='observed_since'?'من أول رصد — حد أدنى':'غير مسجلة',shiftReason(e.reason),e.evidenceAt,c.timeReference])}
async function exportData(kind,button){
 button.disabled=true;$('message').textContent='جارٍ تجهيز شيت كامل حسب التاريخ والفلاتر…';const date=$('day').value,reportId=historical?.report?.id;
 try{
 if(['calls','attendance'].includes(kind)){const d=await api((kind==='attendance'?dashboardQuery(date).replace(/attendance=\d/,'attendance=1'):dashboardQuery(date))+'&all=1');if(date!==$('day').value)throw Error('تغير التاريخ؛ أعد التصدير');if(kind==='calls')csv('calls',['الموظف','التحويلة','النوع','الهاتف','الحالة','بداية المكالمة','وقت آخر حدث','المدة بالثواني','مصدر النسبة'],callsFiltered(d.calls).map(e=>[e.agentName,e.extension,e.callType,e.phone,e.eventType+(e.outsideHours?' — خارج فترة التشغيل':''),e.startedAt,e.occurredAt,e.durationSeconds,e.attributionSource==='history_session'?'سجل أرابيكس + هوية الموظف والتحويلة وقتها':'الإضافة']));else csv('attendance',['الموظف','التحويلة','نوع العملية','البداية','النهاية','المدة في اليوم بالثواني','التوضيح'],attendanceOperations(d).map(s=>[staff.find(e=>e.id===s.employeeId)?.name||'اسم غير متاح',s.extension,operationLabel(s.operation),s.startedAt,s.endedAt||'جارية',s.seconds,s.accuracy]));}
 else if(['sessions','states'].includes(kind)){const d=await api(dashboardQuery(date).replace(/attendance=\d/,'attendance=1')+'&all=1');if(date!==$('day').value)throw Error('تغير التاريخ؛ أعد التصدير');const name=s=>staff.find(e=>e.id===s.employeeId)?.name;if(kind==='sessions')csv('session-durations',['الموظف','التحويلة','البداية','النهاية','مدة الجلسة بالثواني','مدة اليوم بالثواني','دقة المدة'],d.attendance.sessions.filter(matches).map(s=>[name(s),s.extension,s.startedAt,s.endedAt||'غير مؤكدة / جارية',s.durationSeconds,s.daySeconds,s.durationComplete?'مكتملة / جارية':'رصد ناقص']));else csv('state-durations',['الموظف','التحويلة','الحالة','البداية','نهاية الرصد','المدة بالثواني'],d.attendance.states.filter(matches).map(s=>[name(s),s.extension,s.state==='offline'?'منذ الخروج — توضيح فقط':stateLabel(s.state),s.startedAt,s.endedAt,s.durationSeconds]));} else if(kind==='attribution'){const d=await api(dashboardQuery(date)+'&all=1');if(date!==$('day').value)throw Error('تغير التاريخ');csv('history-attribution',['التاريخ الفعلي','بداية المصدر','نهاية المصدر','الهاتف','رقم أرابيكس','الموظف','التحويلة','سبب النسبة أو عدمها','أضيفت لمؤشرات الموظف'],(d.historyAttribution?.rows||[]).map(x=>[x.date,x.start,x.end,x.phone,x.accountId,x.employeeName||'غير منسوبة',x.extension,attributionReason(x.reason),x.included?'نعم':'لا']));} else if(kind==='employees')csv('employee-kpis',['الموظف','الكود','مكالمات','وارد','صادر','مكتملة','متوسط المدة بالثواني','أول دخول','آخر خروج','البريك المكتمل بالثواني','بريكات ناقصة','بريك جارٍ بالثواني','إجمالي البريك بالثواني'],metricsFiltered().map(p=>[staff.find(e=>e.id===p.employeeId)?.name||p.employee,staff.find(e=>e.id===p.employeeId)?.employeeCode,p.calls,p.inbound,p.outbound,p.answered,p.avgHandleTime,p.firstLogin,p.lastLogout,p.breakSeconds,p.unknownBreaks,(daily?.breakTotals||[]).find(t=>t.employeeId===p.employeeId)?.ongoingBreakSeconds||0,(daily?.breakTotals||[]).find(t=>t.employeeId===p.employeeId)?.totalBreakSeconds??p.breakSeconds]));
 else if(kind==='shifts')csv('shift-responsibility',['الموظف','دخول الجلسة','خروج الجلسة','مستبعد','السبب','وقت تطبيق القرار','وقت تسجيل القرار','ملاحظة الإدارة'],shiftsFiltered().map(s=>[staff.find(e=>e.id===s.employeeId)?.name,s.issuedAt?new Date(s.issuedAt).toISOString():'',s.revokedAt?new Date(s.revokedAt).toISOString():'',s.excluded?'نعم':'لا',shiftReason(s.reason),at(s.effectiveAt),s.decidedAt,s.note||'']));
 else if(kind==='roster')csv('employees',['الاسم','الكود','الحالة'],staff.filter(e=>!$('employeeFilter').value||e.id===Number($('employeeFilter').value)).map(e=>[e.name,e.employeeCode,e.active?'نشط':'محذوف']));
 else if(kind==='live')csv('live-snapshot',['وقت السحب','الموظف','التحويلة','الحالة','الهاتف','نوع الطلب','بداية الحالة','مدة الحالة','آخر دليل'],livePeople().map(p=>[new Date().toISOString(),staff.find(e=>e.id===p.employeeId)?.name,p.extension,liveLabel(liveState(p)),p.phone,requestType(p.queue),p.startedAt,['on_call','break'].includes(liveState(p))&&p.startedAt?fmt((Date.now()+offset-Date.parse(p.startedAt))/1000):'غير معروف',p.evidenceAt]));
 else if(kind==='queueLive')csv('queue-live',['وقت اللقطة','نوع الطلب','حساب أرابيكس','الهاتف','الانتظار','الحالة'],(historical?.live?.records||[]).filter(r=>!$('queueFilter').value||r[0]===$('queueFilter').value).map(r=>[historical.live.observedAt,requestType(r[0]),r[2],r[9],r[8],r[10]]));
 else if(kind==='queue')csv('queue-kpis',['رقم القائمة في أرابيكس','نوع الطلب','مكالمات','تم الرد','فائتة محتسبة','متوسط انتظار الرد بالثواني','الرد خلال 10 ثوانٍ %','نسبة المكالمات الفائتة %'],queuesFiltered().map(q=>[q.queue,q.label,q.calls,q.answered,q.abandoned,q.asa,q.sla,q.abandonmentRate]));
 else if(kind==='missed')csv('missed',['نوع الطلب','التاريخ','التوقيت','الهاتف','الانتظار بالثواني','التصنيف'],missedFiltered().map(c=>[requestType(c.queue),c.date,c.end||c.start,c.phone,c.waitSeconds,missedLabel(c.classification)]));
 else if(kind==='context'){if(!context)throw Error('اختر المكالمة أولًا');csv('missed-staff',contextHeaders,contextLines(contextCall,context));}
 else if(kind==='contexts'){if(!reportId)throw Error('لا يوجد سجل لهذا اليوم');const d=await api('/api/history?reportId='+reportId+'&date='+date+'&contexts=1');if(reportId!==historical?.report?.id)throw Error('تغير السجل؛ أعد التصدير');const indices=new Set(missedFiltered().map(c=>c.index));csv('all-missed-staff',contextHeaders,d.contexts.filter(x=>indices.has(x.index)).flatMap(x=>contextLines(x.call,x.context)));}
 else if(kind==='history'){if(!reportId)throw Error('لا يوجد سجل لهذا اليوم');const d=await api('/api/history?reportId='+reportId+'&date='+date+'&all=1');if(date!==$('day').value)throw Error('تغير التاريخ');csv('arabicss-history',['نوع الطلب','حساب أرابيكس','التاريخ الفعلي','البداية','النهاية','المدة','الانتظار','الهاتف','الحالة'],d.records.filter(c=>!$('queueFilter').value||c.queue===$('queueFilter').value).map(c=>[requestType(c.queue),c.accountName,c.date,c.start,c.end,c.durationSeconds,c.waitSeconds,c.phone,c.status+(c.outsideHours?' — خارج فترة التشغيل':'')]));}
 $('message').textContent='تم تجهيز الشيت. CSV يفتح في Excel؛ النصوص والأرقام المفقودة لا تُستبدل بصفر.';
 }catch(e){$('message').textContent='لم يتم التصدير: '+e.message}finally{button.disabled=false}
}
async function login(){ $('loginError').textContent='';$('loginButton').disabled=true;try{const r=await fetch(API+'/api/dashboard?live=1',{headers:{'x-admin-password':$('password').value},cache:'no-store'});if(!r.ok)throw Error(r.status===401?'كلمة مرور الإدارة غير صحيحة':'تعذر الاتصال');sessionStorage.setItem('adminPassword',$('password').value);$('password').value='';$('login').hidden=true;$('dashboard').hidden=false;await refresh(true)}catch(e){$('loginError').textContent=e.message}finally{$('loginButton').disabled=false}}
$('day').value=today();$('day').max=today();
$('loginButton').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};
$('logoutButton').onclick=()=>{generation++;sessionStorage.removeItem('adminPassword');$('dashboard').hidden=true;$('login').hidden=false;clearDay()};
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab)};
$('day').onchange=()=>{generation++;clearDay();refresh(true)};
$('todayButton').onclick=()=>{$('day').value=today();clearDay();refresh(true)};
$('refreshButton').onclick=()=>refresh(true);
for(const id of ['callSearch','callType','callStatus','eventFilter','contextFilter'])$(id).addEventListener('input',()=>{renderDaily();renderLive()});
let filterTimer;for(const id of ['employeeFilter','extensionFilter'])$(id).addEventListener('input',()=>{generation++;clearDay();clearTimeout(filterTimer);filterTimer=setTimeout(()=>refresh(true),350)});
for(const id of ['queueFilter','missedFilter'])$(id).addEventListener('change',()=>{renderHistory();renderLive()});
if($('queueFilter'))$('queueFilter').addEventListener('change',filterSummary);
function moveDay(delta){const d=new Date($('day').value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);const value=d.toISOString().slice(0,10);if(value>today())return;$('day').value=value;generation++;clearDay();refresh(true)}
if($('previousDayButton'))$('previousDayButton').onclick=()=>moveDay(-1);
if($('nextDayButton'))$('nextDayButton').onclick=()=>moveDay(1);
if($('resetFiltersButton'))$('resetFiltersButton').onclick=()=>{for(const id of ['employeeFilter','extensionFilter','queueFilter','callSearch','callType','callStatus','eventFilter','contextFilter','missedFilter','liveStateFilter'])$(id).value='';generation++;clearDay();refresh(true);for(const id of ['employeeFilter','queueFilter','callType','callStatus','eventFilter','contextFilter','missedFilter','liveStateFilter'])$(id).dispatchEvent(new Event('change',{bubbles:true}));};
$('liveStateFilter').addEventListener('change',renderLive);
document.addEventListener('click',e=>{const b=e.target.closest('[data-open-tab]');if(b)showTab(b.dataset.openTab)});
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.filterShortcut){document.querySelector('.filters').scrollIntoView({block:'start'});requestAnimationFrame(()=>{const picker=$('employeeFilter-button');if(picker){picker.focus();picker.click()}else $('employeeFilter').focus()});return}if(button.dataset.export)exportData(button.dataset.export,button);if(button.dataset.missed!==undefined)showContext(Number(button.dataset.missed));if(button.dataset.employee)changeEmployee(Number(button.dataset.employee));if(button.dataset.pin)editPin(Number(button.dataset.pin));if(button.dataset.delete)deleteEmployee(Number(button.dataset.delete));if(button.dataset.shift)changeShift(button.dataset.shift,button.dataset.shiftAction)});
$('addEmployeeButton').onclick=addEmployee;
$('savePinButton').onclick=savePin;$('cancelPinButton').onclick=()=>{$('newPin').value=$('newPinConfirm').value='';$('pinEditor').hidden=true;pinEmployee=null};
$('importButton').onclick=async()=>{const file=$('historyFile').files[0];if(!file){$('message').textContent='اختر ملف Excel أولًا';return}if(file.size>2000000){$('message').textContent='صدّر يومًا واحدًا بحجم أقل من 2MB';return}try{const d=await api('/api/history',{method:'POST',headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},body:file});$('day').value=d.date;clearDay();await refresh(true);$('message').textContent=d.duplicate?'السجل محفوظ بالفعل؛ لم يتكرر':'تم حفظ سجل هذا اليوم'}catch(e){$('message').textContent='لم يُحفظ السجل: '+e.message}};
// Do not rebuild the hidden live tables every second while another workspace
// is open. This keeps desktop and mobile pages responsive without changing
// the live snapshot cadence or any KPI calculations.
setInterval(()=>{if(selectedTab==='live')renderLive();if(selectedTab==='attendance')renderAttendanceDurations()},1000);
// Keep the 5-second polling only on the live view. Historical sections trigger
// costly attribution/report aggregation, so they refresh on demand instead.
setInterval(()=>{if(sessionStorage.getItem('adminPassword')&&selectedTab==='live')refresh()},5000);
if(sessionStorage.getItem('adminPassword')){$('login').hidden=true;$('dashboard').hidden=false;refresh(true)}

