(function(){
  if(!location.hostname.includes('41.38.207.218'))return;
  const apiFetch=async(url,options={})=>{const r=await browser.runtime.sendMessage({type:'KPI_API',path:new URL(url).pathname+new URL(url).search,method:options.method||'GET',headers:options.headers||{},body:options.body});return{ok:r.ok,status:r.status,json:async()=>JSON.parse(r.body)}};
  const API='https://marsad-kpi-live.karim87nu.chatgpt.site',TOKEN='7000865f1220458f86506b41a97cab7d',SESSION='arabicss_kpi_employee_session',QUEUE='arabicss_kpi_offline_queue';
  let employee=JSON.parse(sessionStorage.getItem(SESSION)||'null'),sessionToken=sessionStorage.getItem(SESSION+'_token')||'',lastCall=null,lastDuration=0,breakStarted=null,failures=0,circuitUntil=0,flushing=false,scanTimer=null;
  const inject=()=>{const root=document.documentElement||document.head;if(!root)return false;const s=document.createElement('script');s.src=browser.runtime.getURL('page-hook.js');s.onload=()=>s.remove();root.appendChild(s);return true};if(!inject())document.addEventListener('readystatechange',inject,{once:true});
  const extensionNumber=()=>{const title=document.querySelector('.issabel-callcenter-titulo-consola')?.textContent||'',text=document.querySelector('#kpi-session-box')?.parentElement?.textContent||document.body?.textContent||'';return((title||text).match(/(?:Agent Console:\s*)?(?:IAX2|SIP)\/(\d+)/i)||[])[1]||''};
  const first=(o,keys)=>{for(const k of keys)if(o?.[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return null};
  const seconds=v=>{if(typeof v==='number')return Math.max(0,Math.round(v));const s=String(v??'').trim();if(/^\d+$/.test(s))return Number(s);if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(s))return s.split(':').reduce((a,n)=>a*60+Number(n),0);return 0};
  const callData=(payload,type)=>{const raw=payload?.call||payload?.data||payload||{},phone=String(first(raw,['phone','phonenumber','phone_number','callerid','caller_id','clid','number'])||''),queue=String(first(raw,['queue','queue_number','queueid','queue_id'])||''),occurredAt=String(first(raw,['occurredAt','timestamp','datetime','date','time'])||new Date().toISOString()),supplied=first(raw,['callId','callid','call_id','uniqueid','unique_id','id_llamada','id']),direction=String(first(raw,['direction','callType','call_type','type'])||'').toLowerCase();return{callId:String(supplied||`${extensionNumber()}:${phone||queue||'call'}:${occurredAt.slice(0,19)}`),phone,queue,callType:direction.includes('out')?'outgoing':'incoming',occurredAt,waitSeconds:seconds(first(raw,['waitSeconds','wait_seconds','waiting','wait','queue_wait','queueWait','holdtime'])),durationSeconds:seconds(first(raw,['durationSeconds','duration_seconds','duration','talktime','talk_time'])),state:type,payload}};
  async function enqueue(event){const q=(await browser.storage.local.get(QUEUE))[QUEUE]||[];q.push(event);await browser.storage.local.set({[QUEUE]:q.slice(-2000)})}
  async function send(event){if(!sessionToken||!event.extension)return false;if(Date.now()<circuitUntil){await enqueue(event);return false}const c=new AbortController(),t=setTimeout(()=>c.abort(),4000);try{const r=await apiFetch(`${API}/api/events`,{method:'POST',headers:{'content-type':'application/json','x-device-token':TOKEN,'x-employee-session':sessionToken},body:JSON.stringify(event),keepalive:true,signal:c.signal});if(!r.ok)throw new Error('send');failures=0;const status=document.getElementById('kpi-status');if(status)status.textContent='متصل — Extension '+event.extension;return true}catch{const status=document.getElementById('kpi-status');if(status)status.textContent='تعذر إرسال البيانات — بانتظار الاتصال';failures++;if(failures>=5)circuitUntil=Date.now()+60000;await enqueue(event);return false}finally{clearTimeout(t)}}
  async function flush(){if(!sessionToken||flushing||Date.now()<circuitUntil)return;flushing=true;try{const q=(await browser.storage.local.get(QUEUE))[QUEUE]||[],left=[];for(const event of q.slice(0,25)){try{const r=await apiFetch(`${API}/api/events`,{method:'POST',headers:{'content-type':'application/json','x-device-token':TOKEN,'x-employee-session':sessionToken},body:JSON.stringify(event)});if(!r.ok)left.push(event)}catch{left.push(event)}}left.push(...q.slice(25));await browser.storage.local.set({[QUEUE]:left})}finally{flushing=false}}
  const activity=(eventType,extra={})=>{const at=new Date().toISOString(),ext=extensionNumber();return send({eventType,eventKey:`${ext}:${employee?.id||'none'}:${eventType}:${at}`,extension:ext,occurredAt:at,...extra})};
  function mount(){if(document.getElementById('kpi-session-box'))return;const box=document.createElement('div');box.id='kpi-session-box';box.dir='rtl';box.innerHTML=`<div style="font-weight:700;margin-bottom:9px">جلسة الموظف — KPI</div><div id="kpi-active" style="display:none"><div>الموظف الحالي: <b id="kpi-name"></b></div><div id="kpi-status" style="color:#86efac;margin-top:6px">بانتظار تأكيد الاتصال</div><button id="kpi-end" style="margin-top:10px;width:100%;padding:8px;border:0;border-radius:7px">إنهاء الشيفت</button></div><div id="kpi-form"><select id="kpi-employee" style="box-sizing:border-box;width:100%;padding:12px;border-radius:7px;background:#fff;color:#111827;font:700 17px Arial"><option>جاري التحميل...</option></select><button id="kpi-refresh" style="margin-top:7px;width:100%;padding:7px;border:1px solid #64748b;border-radius:7px;background:transparent;color:#fff">تحديث قائمة الموظفين</button><input id="kpi-pin" type="password" inputmode="numeric" maxlength="8" placeholder="PIN الشخصي" style="box-sizing:border-box;width:100%;padding:12px;margin-top:8px;border-radius:7px;background:#fff;color:#111827;font:700 17px Arial"><button id="kpi-start" style="margin-top:8px;width:100%;padding:9px;border:0;border-radius:7px;background:#2dd4bf;color:#06251e;font:700 18px Arial">بدء الشيفت</button><div id="kpi-error" style="color:#fda4af;margin-top:7px"></div></div>`;document.body.appendChild(box);
    const render=()=>{box.querySelector('#kpi-active').style.display=employee?'block':'none';box.querySelector('#kpi-form').style.display=employee?'none':'block';box.querySelector('#kpi-name').textContent=employee?.name||'';box.style.cssText='position:fixed;z-index:2147483647;color:#fff;border:1px solid #2dd4bf;padding:18px;font:17px Arial;box-shadow:0 8px 30px #0009;'+(employee?'left:16px;bottom:16px;width:280px;border-radius:12px;background:#142033':'inset:0;display:grid;place-content:center;text-align:center;background:#101b2bee')};
    const refresh=async()=>{if(employee)return;const select=box.querySelector('#kpi-employee'),current=select.value;select.innerHTML='<option value="">جاري تحميل الموظفين...</option>';try{const r=await apiFetch(`${API}/api/employees/list?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();select.innerHTML='<option value="">اختر اسم الموظف</option>'+d.employees.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;box.querySelector('#kpi-error').textContent=d.employees.length?'':'لا يوجد موظفون نشطون'}catch{select.innerHTML='<option value="">تعذر تحميل القائمة</option>';box.querySelector('#kpi-error').textContent='تعذر الاتصال — اضغط تحديث القائمة'}};
    box.querySelector('#kpi-refresh').onclick=refresh;window.addEventListener('focus',refresh);setInterval(refresh,15000);refresh();
    box.querySelector('#kpi-start').onclick=async()=>{const employeeId=Number(box.querySelector('#kpi-employee').value),pin=box.querySelector('#kpi-pin').value,ext=extensionNumber();if(!employeeId||!/^\d{4,8}$/.test(pin)){box.querySelector('#kpi-error').textContent='اختر اسمك وأدخل PIN الصحيح';return}const r=await apiFetch(`${API}/api/session/start`,{method:'POST',headers:{'content-type':'application/json','x-device-token':TOKEN},body:JSON.stringify({employeeId,pin,extension:ext})});if(!r.ok){box.querySelector('#kpi-error').textContent='الـPIN غير صحيح';return}const d=await r.json();employee=d.employee;sessionToken=d.token;sessionStorage.setItem(SESSION,JSON.stringify(employee));sessionStorage.setItem(SESSION+'_token',sessionToken);box.querySelector('#kpi-pin').value='';render();if(ext){await activity('session_login',{state:'verified'});flush();scan()}else{box.querySelector('#kpi-status').textContent='تم تأكيد هويتك — سجل دخول Arabicss ثم افتح Agent Console'}};
    box.querySelector('#kpi-end').onclick=()=>{if(lastCall){alert('لا يمكن إنهاء الشيفت أثناء مكالمة جارية');return}activity('session_logout',{state:'manual'});employee=null;sessionToken='';sessionStorage.removeItem(SESSION);sessionStorage.removeItem(SESSION+'_token');render();refresh()};render();
  }
  function scan(){if(!employee)return;const ext=extensionNumber();if(!ext)return;const info=document.querySelector('#issabel-callcenter-llamada-info')?.innerText||'',callId=(info.match(/Internal Call ID:\s*([^\s]+)/i)||[])[1],phone=(info.match(/Phone number:\s*([+\d]+)/i)||[])[1],timer=document.querySelector('#issabel-callcenter-cronometro')?.textContent||'00:00:00',duration=seconds(timer);if(callId)lastDuration=duration;if(callId&&callId!==lastCall){lastCall=callId;send({eventType:'agentlinked',eventKey:`${ext}:${callId}:start`,callId,extension:ext,phone,callType:callId.startsWith('incoming')?'incoming':'outgoing',occurredAt:new Date().toISOString(),durationSeconds:0})}if(lastCall&&!callId){send({eventType:'agentunlinked',eventKey:`${ext}:${lastCall}:end`,callId:lastCall,extension:ext,occurredAt:new Date().toISOString(),durationSeconds:lastDuration});lastCall=null;lastDuration=0}}
  const scheduleScan=()=>{if(scanTimer)return;scanTimer=setTimeout(()=>{scanTimer=null;scan()},250)};
  window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.source!=='ARABICSS_KPI_SSE'||!employee)return;let payload={};try{payload=JSON.parse(e.data.data||'{}')}catch{payload={raw:String(e.data.data||'')}}const type=String(e.data.type||'').toLowerCase(),ext=extensionNumber();if(type==='breakenter'){breakStarted=new Date().toISOString();activity('break_start',{state:String(payload.breakname||payload.break||'Break'),payload})}else if(type==='breakexit'){activity('break_end',{durationSeconds:breakStarted?Math.round((Date.now()-new Date(breakStarted).getTime())/1000):0,state:'Available',payload});breakStarted=null}else if(type==='agentloggedout')activity('arabicss_logout',{payload});else if(type==='agentloggedin')activity('arabicss_login',{payload});else if(type==='agentlinked'){const c=callData(payload,type);lastCall=c.callId;lastDuration=c.durationSeconds;send({...c,eventType:'agentlinked',eventKey:`${ext}:${c.callId}:start`,extension:ext})}else if(type==='agentunlinked'){const c=callData(payload,type),id=lastCall||c.callId;send({...c,eventType:'agentunlinked',eventKey:`${ext}:${id}:end`,callId:id,extension:ext,durationSeconds:c.durationSeconds||lastDuration});lastCall=null;lastDuration=0}else if(/abandon|hangup.*queue|queue.*leave/.test(type)){const c=callData(payload,type);send({...c,eventType:'abandoned',eventKey:`${ext}:${c.callId}:abandoned`,extension:ext})}else if(/queue.*(enter|join)|call.*queue/.test(type)){const c=callData(payload,type);send({...c,eventType:'queue_enter',eventKey:`${ext}:${c.callId}:queue`,extension:ext})}});
  function boot(){const style=document.createElement('style');style.textContent='#kpi-session-box select,#kpi-session-box input{background:#ffffff!important;color:#111827!important;opacity:1!important;font:700 17px Arial!important}#kpi-session-box option{background:#ffffff!important;color:#111827!important}#kpi-session-box input::placeholder{color:#475569!important;opacity:1!important}#kpi-session-box button{cursor:pointer!important;opacity:1!important}#kpi-error{font-size:16px!important;color:#ffb4b4!important}';document.documentElement.appendChild(style);mount();new MutationObserver(scheduleScan).observe(document.body,{childList:true,subtree:true,characterData:true});scan()}window.addEventListener('online',flush);setInterval(flush,10000);setInterval(()=>{if(employee&&sessionToken&&extensionNumber())activity('heartbeat',{state:lastCall?'on_call':breakStarted?'break':'ready'})},30000);window.addEventListener('pagehide',()=>{if(employee)activity('page_closed',{state:'unexpected_or_navigation'})});if(document.body)boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});
})();
